// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/markns/chargebee-golang/models"
)

// ChangeTermEndEstimateReader is a Reader for the ChangeTermEndEstimate structure.
type ChangeTermEndEstimateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ChangeTermEndEstimateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewChangeTermEndEstimateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewChangeTermEndEstimateOK creates a ChangeTermEndEstimateOK with default headers values
func NewChangeTermEndEstimateOK() *ChangeTermEndEstimateOK {
	return &ChangeTermEndEstimateOK{}
}

/*ChangeTermEndEstimateOK handles this case with default header values.

changeTermEndEstimate response
*/
type ChangeTermEndEstimateOK struct {
	Payload *models.EstimateResponse
}

func (o *ChangeTermEndEstimateOK) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{id}/change_term_end_estimate][%d] changeTermEndEstimateOK  %+v", 200, o.Payload)
}

func (o *ChangeTermEndEstimateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EstimateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
