// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCloseInvoiceParams creates a new CloseInvoiceParams object
// with the default values initialized.
func NewCloseInvoiceParams() *CloseInvoiceParams {
	var ()
	return &CloseInvoiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCloseInvoiceParamsWithTimeout creates a new CloseInvoiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCloseInvoiceParamsWithTimeout(timeout time.Duration) *CloseInvoiceParams {
	var ()
	return &CloseInvoiceParams{

		timeout: timeout,
	}
}

// NewCloseInvoiceParamsWithContext creates a new CloseInvoiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCloseInvoiceParamsWithContext(ctx context.Context) *CloseInvoiceParams {
	var ()
	return &CloseInvoiceParams{

		Context: ctx,
	}
}

// NewCloseInvoiceParamsWithHTTPClient creates a new CloseInvoiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCloseInvoiceParamsWithHTTPClient(client *http.Client) *CloseInvoiceParams {
	var ()
	return &CloseInvoiceParams{
		HTTPClient: client,
	}
}

/*CloseInvoiceParams contains all the parameters to send to the API endpoint
for the close invoice operation typically these are written to a http.Request
*/
type CloseInvoiceParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the close invoice params
func (o *CloseInvoiceParams) WithTimeout(timeout time.Duration) *CloseInvoiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the close invoice params
func (o *CloseInvoiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the close invoice params
func (o *CloseInvoiceParams) WithContext(ctx context.Context) *CloseInvoiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the close invoice params
func (o *CloseInvoiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the close invoice params
func (o *CloseInvoiceParams) WithHTTPClient(client *http.Client) *CloseInvoiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the close invoice params
func (o *CloseInvoiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the close invoice params
func (o *CloseInvoiceParams) WithID(id string) *CloseInvoiceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the close invoice params
func (o *CloseInvoiceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CloseInvoiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
