// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// NewCopyCouponParams creates a new CopyCouponParams object
// with the default values initialized.
func NewCopyCouponParams() *CopyCouponParams {
	var ()
	return &CopyCouponParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCopyCouponParamsWithTimeout creates a new CopyCouponParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCopyCouponParamsWithTimeout(timeout time.Duration) *CopyCouponParams {
	var ()
	return &CopyCouponParams{

		timeout: timeout,
	}
}

// NewCopyCouponParamsWithContext creates a new CopyCouponParams object
// with the default values initialized, and the ability to set a context for a request
func NewCopyCouponParamsWithContext(ctx context.Context) *CopyCouponParams {
	var ()
	return &CopyCouponParams{

		Context: ctx,
	}
}

// NewCopyCouponParamsWithHTTPClient creates a new CopyCouponParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCopyCouponParamsWithHTTPClient(client *http.Client) *CopyCouponParams {
	var ()
	return &CopyCouponParams{
		HTTPClient: client,
	}
}

/*CopyCouponParams contains all the parameters to send to the API endpoint
for the copy coupon operation typically these are written to a http.Request
*/
type CopyCouponParams struct {

	/*CouponCopyRequest*/
	CouponCopyRequest *models.CouponCopyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the copy coupon params
func (o *CopyCouponParams) WithTimeout(timeout time.Duration) *CopyCouponParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the copy coupon params
func (o *CopyCouponParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the copy coupon params
func (o *CopyCouponParams) WithContext(ctx context.Context) *CopyCouponParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the copy coupon params
func (o *CopyCouponParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the copy coupon params
func (o *CopyCouponParams) WithHTTPClient(client *http.Client) *CopyCouponParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the copy coupon params
func (o *CopyCouponParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCouponCopyRequest adds the couponCopyRequest to the copy coupon params
func (o *CopyCouponParams) WithCouponCopyRequest(couponCopyRequest *models.CouponCopyRequest) *CopyCouponParams {
	o.SetCouponCopyRequest(couponCopyRequest)
	return o
}

// SetCouponCopyRequest adds the couponCopyRequest to the copy coupon params
func (o *CopyCouponParams) SetCouponCopyRequest(couponCopyRequest *models.CouponCopyRequest) {
	o.CouponCopyRequest = couponCopyRequest
}

// WriteToRequest writes these params to a swagger request
func (o *CopyCouponParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CouponCopyRequest != nil {
		if err := r.SetBodyParam(o.CouponCopyRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
