// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/markns/chargebee-golang/models"
)

// NewCreateCouponCodeParams creates a new CreateCouponCodeParams object
// with the default values initialized.
func NewCreateCouponCodeParams() *CreateCouponCodeParams {
	var ()
	return &CreateCouponCodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateCouponCodeParamsWithTimeout creates a new CreateCouponCodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateCouponCodeParamsWithTimeout(timeout time.Duration) *CreateCouponCodeParams {
	var ()
	return &CreateCouponCodeParams{

		timeout: timeout,
	}
}

// NewCreateCouponCodeParamsWithContext creates a new CreateCouponCodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateCouponCodeParamsWithContext(ctx context.Context) *CreateCouponCodeParams {
	var ()
	return &CreateCouponCodeParams{

		Context: ctx,
	}
}

// NewCreateCouponCodeParamsWithHTTPClient creates a new CreateCouponCodeParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateCouponCodeParamsWithHTTPClient(client *http.Client) *CreateCouponCodeParams {
	var ()
	return &CreateCouponCodeParams{
		HTTPClient: client,
	}
}

/*CreateCouponCodeParams contains all the parameters to send to the API endpoint
for the create coupon code operation typically these are written to a http.Request
*/
type CreateCouponCodeParams struct {

	/*CouponCodeCreateRequest*/
	CouponCodeCreateRequest *models.CouponCodeCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create coupon code params
func (o *CreateCouponCodeParams) WithTimeout(timeout time.Duration) *CreateCouponCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create coupon code params
func (o *CreateCouponCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create coupon code params
func (o *CreateCouponCodeParams) WithContext(ctx context.Context) *CreateCouponCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create coupon code params
func (o *CreateCouponCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create coupon code params
func (o *CreateCouponCodeParams) WithHTTPClient(client *http.Client) *CreateCouponCodeParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create coupon code params
func (o *CreateCouponCodeParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCouponCodeCreateRequest adds the couponCodeCreateRequest to the create coupon code params
func (o *CreateCouponCodeParams) WithCouponCodeCreateRequest(couponCodeCreateRequest *models.CouponCodeCreateRequest) *CreateCouponCodeParams {
	o.SetCouponCodeCreateRequest(couponCodeCreateRequest)
	return o
}

// SetCouponCodeCreateRequest adds the couponCodeCreateRequest to the create coupon code params
func (o *CreateCouponCodeParams) SetCouponCodeCreateRequest(couponCodeCreateRequest *models.CouponCodeCreateRequest) {
	o.CouponCodeCreateRequest = couponCodeCreateRequest
}

// WriteToRequest writes these params to a swagger request
func (o *CreateCouponCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CouponCodeCreateRequest == nil {
		o.CouponCodeCreateRequest = new(models.CouponCodeCreateRequest)
	}

	if err := r.SetBodyParam(o.CouponCodeCreateRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
