// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// NewCreateInvoiceParams creates a new CreateInvoiceParams object
// with the default values initialized.
func NewCreateInvoiceParams() *CreateInvoiceParams {
	var ()
	return &CreateInvoiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateInvoiceParamsWithTimeout creates a new CreateInvoiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateInvoiceParamsWithTimeout(timeout time.Duration) *CreateInvoiceParams {
	var ()
	return &CreateInvoiceParams{

		timeout: timeout,
	}
}

// NewCreateInvoiceParamsWithContext creates a new CreateInvoiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateInvoiceParamsWithContext(ctx context.Context) *CreateInvoiceParams {
	var ()
	return &CreateInvoiceParams{

		Context: ctx,
	}
}

// NewCreateInvoiceParamsWithHTTPClient creates a new CreateInvoiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateInvoiceParamsWithHTTPClient(client *http.Client) *CreateInvoiceParams {
	var ()
	return &CreateInvoiceParams{
		HTTPClient: client,
	}
}

/*CreateInvoiceParams contains all the parameters to send to the API endpoint
for the create invoice operation typically these are written to a http.Request
*/
type CreateInvoiceParams struct {

	/*InvoiceCreateRequest*/
	InvoiceCreateRequest *models.InvoiceCreateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create invoice params
func (o *CreateInvoiceParams) WithTimeout(timeout time.Duration) *CreateInvoiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create invoice params
func (o *CreateInvoiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create invoice params
func (o *CreateInvoiceParams) WithContext(ctx context.Context) *CreateInvoiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create invoice params
func (o *CreateInvoiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create invoice params
func (o *CreateInvoiceParams) WithHTTPClient(client *http.Client) *CreateInvoiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create invoice params
func (o *CreateInvoiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithInvoiceCreateRequest adds the invoiceCreateRequest to the create invoice params
func (o *CreateInvoiceParams) WithInvoiceCreateRequest(invoiceCreateRequest *models.InvoiceCreateRequest) *CreateInvoiceParams {
	o.SetInvoiceCreateRequest(invoiceCreateRequest)
	return o
}

// SetInvoiceCreateRequest adds the invoiceCreateRequest to the create invoice params
func (o *CreateInvoiceParams) SetInvoiceCreateRequest(invoiceCreateRequest *models.InvoiceCreateRequest) {
	o.InvoiceCreateRequest = invoiceCreateRequest
}

// WriteToRequest writes these params to a swagger request
func (o *CreateInvoiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.InvoiceCreateRequest != nil {
		if err := r.SetBodyParam(o.InvoiceCreateRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
