// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// CreateCouponSetReader is a Reader for the CreateCouponSet structure.
type CreateCouponSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateCouponSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateCouponSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateCouponSetOK creates a CreateCouponSetOK with default headers values
func NewCreateCouponSetOK() *CreateCouponSetOK {
	return &CreateCouponSetOK{}
}

/*CreateCouponSetOK handles this case with default header values.

createCouponSet response
*/
type CreateCouponSetOK struct {
	Payload *models.CouponSetResponse
}

func (o *CreateCouponSetOK) Error() string {
	return fmt.Sprintf("[POST /coupon_sets][%d] createCouponSetOK  %+v", 200, o.Payload)
}

func (o *CreateCouponSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CouponSetResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
