// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// NewCreateUsingTempTokenPaymentSourceParams creates a new CreateUsingTempTokenPaymentSourceParams object
// with the default values initialized.
func NewCreateUsingTempTokenPaymentSourceParams() *CreateUsingTempTokenPaymentSourceParams {
	var ()
	return &CreateUsingTempTokenPaymentSourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateUsingTempTokenPaymentSourceParamsWithTimeout creates a new CreateUsingTempTokenPaymentSourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateUsingTempTokenPaymentSourceParamsWithTimeout(timeout time.Duration) *CreateUsingTempTokenPaymentSourceParams {
	var ()
	return &CreateUsingTempTokenPaymentSourceParams{

		timeout: timeout,
	}
}

// NewCreateUsingTempTokenPaymentSourceParamsWithContext creates a new CreateUsingTempTokenPaymentSourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateUsingTempTokenPaymentSourceParamsWithContext(ctx context.Context) *CreateUsingTempTokenPaymentSourceParams {
	var ()
	return &CreateUsingTempTokenPaymentSourceParams{

		Context: ctx,
	}
}

// NewCreateUsingTempTokenPaymentSourceParamsWithHTTPClient creates a new CreateUsingTempTokenPaymentSourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateUsingTempTokenPaymentSourceParamsWithHTTPClient(client *http.Client) *CreateUsingTempTokenPaymentSourceParams {
	var ()
	return &CreateUsingTempTokenPaymentSourceParams{
		HTTPClient: client,
	}
}

/*CreateUsingTempTokenPaymentSourceParams contains all the parameters to send to the API endpoint
for the create using temp token payment source operation typically these are written to a http.Request
*/
type CreateUsingTempTokenPaymentSourceParams struct {

	/*PaymentSourceCreateUsingTempTokenRequest*/
	PaymentSourceCreateUsingTempTokenRequest *models.PaymentSourceCreateUsingTempTokenRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create using temp token payment source params
func (o *CreateUsingTempTokenPaymentSourceParams) WithTimeout(timeout time.Duration) *CreateUsingTempTokenPaymentSourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create using temp token payment source params
func (o *CreateUsingTempTokenPaymentSourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create using temp token payment source params
func (o *CreateUsingTempTokenPaymentSourceParams) WithContext(ctx context.Context) *CreateUsingTempTokenPaymentSourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create using temp token payment source params
func (o *CreateUsingTempTokenPaymentSourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create using temp token payment source params
func (o *CreateUsingTempTokenPaymentSourceParams) WithHTTPClient(client *http.Client) *CreateUsingTempTokenPaymentSourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create using temp token payment source params
func (o *CreateUsingTempTokenPaymentSourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPaymentSourceCreateUsingTempTokenRequest adds the paymentSourceCreateUsingTempTokenRequest to the create using temp token payment source params
func (o *CreateUsingTempTokenPaymentSourceParams) WithPaymentSourceCreateUsingTempTokenRequest(paymentSourceCreateUsingTempTokenRequest *models.PaymentSourceCreateUsingTempTokenRequest) *CreateUsingTempTokenPaymentSourceParams {
	o.SetPaymentSourceCreateUsingTempTokenRequest(paymentSourceCreateUsingTempTokenRequest)
	return o
}

// SetPaymentSourceCreateUsingTempTokenRequest adds the paymentSourceCreateUsingTempTokenRequest to the create using temp token payment source params
func (o *CreateUsingTempTokenPaymentSourceParams) SetPaymentSourceCreateUsingTempTokenRequest(paymentSourceCreateUsingTempTokenRequest *models.PaymentSourceCreateUsingTempTokenRequest) {
	o.PaymentSourceCreateUsingTempTokenRequest = paymentSourceCreateUsingTempTokenRequest
}

// WriteToRequest writes these params to a swagger request
func (o *CreateUsingTempTokenPaymentSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PaymentSourceCreateUsingTempTokenRequest != nil {
		if err := r.SetBodyParam(o.PaymentSourceCreateUsingTempTokenRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
