// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreditNotesForCustomerCreditNoteParams creates a new CreditNotesForCustomerCreditNoteParams object
// with the default values initialized.
func NewCreditNotesForCustomerCreditNoteParams() *CreditNotesForCustomerCreditNoteParams {
	var ()
	return &CreditNotesForCustomerCreditNoteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreditNotesForCustomerCreditNoteParamsWithTimeout creates a new CreditNotesForCustomerCreditNoteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreditNotesForCustomerCreditNoteParamsWithTimeout(timeout time.Duration) *CreditNotesForCustomerCreditNoteParams {
	var ()
	return &CreditNotesForCustomerCreditNoteParams{

		timeout: timeout,
	}
}

// NewCreditNotesForCustomerCreditNoteParamsWithContext creates a new CreditNotesForCustomerCreditNoteParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreditNotesForCustomerCreditNoteParamsWithContext(ctx context.Context) *CreditNotesForCustomerCreditNoteParams {
	var ()
	return &CreditNotesForCustomerCreditNoteParams{

		Context: ctx,
	}
}

// NewCreditNotesForCustomerCreditNoteParamsWithHTTPClient creates a new CreditNotesForCustomerCreditNoteParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreditNotesForCustomerCreditNoteParamsWithHTTPClient(client *http.Client) *CreditNotesForCustomerCreditNoteParams {
	var ()
	return &CreditNotesForCustomerCreditNoteParams{
		HTTPClient: client,
	}
}

/*CreditNotesForCustomerCreditNoteParams contains all the parameters to send to the API endpoint
for the credit notes for customer credit note operation typically these are written to a http.Request
*/
type CreditNotesForCustomerCreditNoteParams struct {

	/*ID*/
	ID string
	/*Limit*/
	Limit *int32
	/*Offset*/
	Offset *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) WithTimeout(timeout time.Duration) *CreditNotesForCustomerCreditNoteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) WithContext(ctx context.Context) *CreditNotesForCustomerCreditNoteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) WithHTTPClient(client *http.Client) *CreditNotesForCustomerCreditNoteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) WithID(id string) *CreditNotesForCustomerCreditNoteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) SetID(id string) {
	o.ID = id
}

// WithLimit adds the limit to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) WithLimit(limit *int32) *CreditNotesForCustomerCreditNoteParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) SetLimit(limit *int32) {
	o.Limit = limit
}

// WithOffset adds the offset to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) WithOffset(offset *string) *CreditNotesForCustomerCreditNoteParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the credit notes for customer credit note params
func (o *CreditNotesForCustomerCreditNoteParams) SetOffset(offset *string) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *CreditNotesForCustomerCreditNoteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int32
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt32(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset string
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := qrOffset
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
