// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteCouponSetParams creates a new DeleteCouponSetParams object
// with the default values initialized.
func NewDeleteCouponSetParams() *DeleteCouponSetParams {
	var ()
	return &DeleteCouponSetParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteCouponSetParamsWithTimeout creates a new DeleteCouponSetParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteCouponSetParamsWithTimeout(timeout time.Duration) *DeleteCouponSetParams {
	var ()
	return &DeleteCouponSetParams{

		timeout: timeout,
	}
}

// NewDeleteCouponSetParamsWithContext creates a new DeleteCouponSetParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteCouponSetParamsWithContext(ctx context.Context) *DeleteCouponSetParams {
	var ()
	return &DeleteCouponSetParams{

		Context: ctx,
	}
}

// NewDeleteCouponSetParamsWithHTTPClient creates a new DeleteCouponSetParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteCouponSetParamsWithHTTPClient(client *http.Client) *DeleteCouponSetParams {
	var ()
	return &DeleteCouponSetParams{
		HTTPClient: client,
	}
}

/*DeleteCouponSetParams contains all the parameters to send to the API endpoint
for the delete coupon set operation typically these are written to a http.Request
*/
type DeleteCouponSetParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete coupon set params
func (o *DeleteCouponSetParams) WithTimeout(timeout time.Duration) *DeleteCouponSetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete coupon set params
func (o *DeleteCouponSetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete coupon set params
func (o *DeleteCouponSetParams) WithContext(ctx context.Context) *DeleteCouponSetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete coupon set params
func (o *DeleteCouponSetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete coupon set params
func (o *DeleteCouponSetParams) WithHTTPClient(client *http.Client) *DeleteCouponSetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete coupon set params
func (o *DeleteCouponSetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete coupon set params
func (o *DeleteCouponSetParams) WithID(id string) *DeleteCouponSetParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete coupon set params
func (o *DeleteCouponSetParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteCouponSetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
