// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/markns/chargebee-golang/models"
)

// DeleteCustomerReader is a Reader for the DeleteCustomer structure.
type DeleteCustomerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteCustomerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteCustomerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteCustomerOK creates a DeleteCustomerOK with default headers values
func NewDeleteCustomerOK() *DeleteCustomerOK {
	return &DeleteCustomerOK{}
}

/*DeleteCustomerOK handles this case with default header values.

deleteCustomer response
*/
type DeleteCustomerOK struct {
	Payload *models.CustomerResponse
}

func (o *DeleteCustomerOK) Error() string {
	return fmt.Sprintf("[POST /customers/{id}/delete][%d] deleteCustomerOK  %+v", 200, o.Payload)
}

func (o *DeleteCustomerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CustomerResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
