// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// ListCouponSetReader is a Reader for the ListCouponSet structure.
type ListCouponSetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListCouponSetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListCouponSetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListCouponSetOK creates a ListCouponSetOK with default headers values
func NewListCouponSetOK() *ListCouponSetOK {
	return &ListCouponSetOK{}
}

/*ListCouponSetOK handles this case with default header values.

listCouponSet response
*/
type ListCouponSetOK struct {
	Payload *models.ListCouponSetOKBody
}

func (o *ListCouponSetOK) Error() string {
	return fmt.Sprintf("[GET /coupon_sets][%d] listCouponSetOK  %+v", 200, o.Payload)
}

func (o *ListCouponSetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ListCouponSetOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
