// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListPlanParams creates a new ListPlanParams object
// with the default values initialized.
func NewListPlanParams() *ListPlanParams {

	return &ListPlanParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListPlanParamsWithTimeout creates a new ListPlanParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListPlanParamsWithTimeout(timeout time.Duration) *ListPlanParams {

	return &ListPlanParams{

		timeout: timeout,
	}
}

// NewListPlanParamsWithContext creates a new ListPlanParams object
// with the default values initialized, and the ability to set a context for a request
func NewListPlanParamsWithContext(ctx context.Context) *ListPlanParams {

	return &ListPlanParams{

		Context: ctx,
	}
}

// NewListPlanParamsWithHTTPClient creates a new ListPlanParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewListPlanParamsWithHTTPClient(client *http.Client) *ListPlanParams {

	return &ListPlanParams{
		HTTPClient: client,
	}
}

/*ListPlanParams contains all the parameters to send to the API endpoint
for the list plan operation typically these are written to a http.Request
*/
type ListPlanParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list plan params
func (o *ListPlanParams) WithTimeout(timeout time.Duration) *ListPlanParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list plan params
func (o *ListPlanParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list plan params
func (o *ListPlanParams) WithContext(ctx context.Context) *ListPlanParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list plan params
func (o *ListPlanParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list plan params
func (o *ListPlanParams) WithHTTPClient(client *http.Client) *ListPlanParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list plan params
func (o *ListPlanParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ListPlanParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
