// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPdfInvoiceParams creates a new PdfInvoiceParams object
// with the default values initialized.
func NewPdfInvoiceParams() *PdfInvoiceParams {
	var ()
	return &PdfInvoiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPdfInvoiceParamsWithTimeout creates a new PdfInvoiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPdfInvoiceParamsWithTimeout(timeout time.Duration) *PdfInvoiceParams {
	var ()
	return &PdfInvoiceParams{

		timeout: timeout,
	}
}

// NewPdfInvoiceParamsWithContext creates a new PdfInvoiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewPdfInvoiceParamsWithContext(ctx context.Context) *PdfInvoiceParams {
	var ()
	return &PdfInvoiceParams{

		Context: ctx,
	}
}

// NewPdfInvoiceParamsWithHTTPClient creates a new PdfInvoiceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPdfInvoiceParamsWithHTTPClient(client *http.Client) *PdfInvoiceParams {
	var ()
	return &PdfInvoiceParams{
		HTTPClient: client,
	}
}

/*PdfInvoiceParams contains all the parameters to send to the API endpoint
for the pdf invoice operation typically these are written to a http.Request
*/
type PdfInvoiceParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the pdf invoice params
func (o *PdfInvoiceParams) WithTimeout(timeout time.Duration) *PdfInvoiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the pdf invoice params
func (o *PdfInvoiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the pdf invoice params
func (o *PdfInvoiceParams) WithContext(ctx context.Context) *PdfInvoiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the pdf invoice params
func (o *PdfInvoiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the pdf invoice params
func (o *PdfInvoiceParams) WithHTTPClient(client *http.Client) *PdfInvoiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the pdf invoice params
func (o *PdfInvoiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the pdf invoice params
func (o *PdfInvoiceParams) WithID(id string) *PdfInvoiceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the pdf invoice params
func (o *PdfInvoiceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PdfInvoiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
