// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// RemoveScheduledChangesSubscriptionReader is a Reader for the RemoveScheduledChangesSubscription structure.
type RemoveScheduledChangesSubscriptionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RemoveScheduledChangesSubscriptionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRemoveScheduledChangesSubscriptionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRemoveScheduledChangesSubscriptionOK creates a RemoveScheduledChangesSubscriptionOK with default headers values
func NewRemoveScheduledChangesSubscriptionOK() *RemoveScheduledChangesSubscriptionOK {
	return &RemoveScheduledChangesSubscriptionOK{}
}

/*RemoveScheduledChangesSubscriptionOK handles this case with default header values.

removeScheduledChangesSubscription response
*/
type RemoveScheduledChangesSubscriptionOK struct {
	Payload *models.SubscriptionResponse
}

func (o *RemoveScheduledChangesSubscriptionOK) Error() string {
	return fmt.Sprintf("[POST /subscriptions/{id}/remove_scheduled_changes][%d] removeScheduledChangesSubscriptionOK  %+v", 200, o.Payload)
}

func (o *RemoveScheduledChangesSubscriptionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SubscriptionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
