// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/markns/chargebee-golang/models"
)

// NewRemoveScheduledCancellationSubscriptionParams creates a new RemoveScheduledCancellationSubscriptionParams object
// with the default values initialized.
func NewRemoveScheduledCancellationSubscriptionParams() *RemoveScheduledCancellationSubscriptionParams {
	var ()
	return &RemoveScheduledCancellationSubscriptionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRemoveScheduledCancellationSubscriptionParamsWithTimeout creates a new RemoveScheduledCancellationSubscriptionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRemoveScheduledCancellationSubscriptionParamsWithTimeout(timeout time.Duration) *RemoveScheduledCancellationSubscriptionParams {
	var ()
	return &RemoveScheduledCancellationSubscriptionParams{

		timeout: timeout,
	}
}

// NewRemoveScheduledCancellationSubscriptionParamsWithContext creates a new RemoveScheduledCancellationSubscriptionParams object
// with the default values initialized, and the ability to set a context for a request
func NewRemoveScheduledCancellationSubscriptionParamsWithContext(ctx context.Context) *RemoveScheduledCancellationSubscriptionParams {
	var ()
	return &RemoveScheduledCancellationSubscriptionParams{

		Context: ctx,
	}
}

// NewRemoveScheduledCancellationSubscriptionParamsWithHTTPClient creates a new RemoveScheduledCancellationSubscriptionParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRemoveScheduledCancellationSubscriptionParamsWithHTTPClient(client *http.Client) *RemoveScheduledCancellationSubscriptionParams {
	var ()
	return &RemoveScheduledCancellationSubscriptionParams{
		HTTPClient: client,
	}
}

/*RemoveScheduledCancellationSubscriptionParams contains all the parameters to send to the API endpoint
for the remove scheduled cancellation subscription operation typically these are written to a http.Request
*/
type RemoveScheduledCancellationSubscriptionParams struct {

	/*SubscriptionRemoveScheduledCancellationRequest*/
	SubscriptionRemoveScheduledCancellationRequest *models.SubscriptionRemoveScheduledCancellationRequest
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the remove scheduled cancellation subscription params
func (o *RemoveScheduledCancellationSubscriptionParams) WithTimeout(timeout time.Duration) *RemoveScheduledCancellationSubscriptionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the remove scheduled cancellation subscription params
func (o *RemoveScheduledCancellationSubscriptionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the remove scheduled cancellation subscription params
func (o *RemoveScheduledCancellationSubscriptionParams) WithContext(ctx context.Context) *RemoveScheduledCancellationSubscriptionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the remove scheduled cancellation subscription params
func (o *RemoveScheduledCancellationSubscriptionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the remove scheduled cancellation subscription params
func (o *RemoveScheduledCancellationSubscriptionParams) WithHTTPClient(client *http.Client) *RemoveScheduledCancellationSubscriptionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the remove scheduled cancellation subscription params
func (o *RemoveScheduledCancellationSubscriptionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithSubscriptionRemoveScheduledCancellationRequest adds the subscriptionRemoveScheduledCancellationRequest to the remove scheduled cancellation subscription params
func (o *RemoveScheduledCancellationSubscriptionParams) WithSubscriptionRemoveScheduledCancellationRequest(subscriptionRemoveScheduledCancellationRequest *models.SubscriptionRemoveScheduledCancellationRequest) *RemoveScheduledCancellationSubscriptionParams {
	o.SetSubscriptionRemoveScheduledCancellationRequest(subscriptionRemoveScheduledCancellationRequest)
	return o
}

// SetSubscriptionRemoveScheduledCancellationRequest adds the subscriptionRemoveScheduledCancellationRequest to the remove scheduled cancellation subscription params
func (o *RemoveScheduledCancellationSubscriptionParams) SetSubscriptionRemoveScheduledCancellationRequest(subscriptionRemoveScheduledCancellationRequest *models.SubscriptionRemoveScheduledCancellationRequest) {
	o.SubscriptionRemoveScheduledCancellationRequest = subscriptionRemoveScheduledCancellationRequest
}

// WithID adds the id to the remove scheduled cancellation subscription params
func (o *RemoveScheduledCancellationSubscriptionParams) WithID(id string) *RemoveScheduledCancellationSubscriptionParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the remove scheduled cancellation subscription params
func (o *RemoveScheduledCancellationSubscriptionParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RemoveScheduledCancellationSubscriptionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.SubscriptionRemoveScheduledCancellationRequest == nil {
		o.SubscriptionRemoveScheduledCancellationRequest = new(models.SubscriptionRemoveScheduledCancellationRequest)
	}

	if err := r.SetBodyParam(o.SubscriptionRemoveScheduledCancellationRequest); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
