// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewRetrieveAddonParams creates a new RetrieveAddonParams object
// with the default values initialized.
func NewRetrieveAddonParams() *RetrieveAddonParams {
	var ()
	return &RetrieveAddonParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveAddonParamsWithTimeout creates a new RetrieveAddonParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRetrieveAddonParamsWithTimeout(timeout time.Duration) *RetrieveAddonParams {
	var ()
	return &RetrieveAddonParams{

		timeout: timeout,
	}
}

// NewRetrieveAddonParamsWithContext creates a new RetrieveAddonParams object
// with the default values initialized, and the ability to set a context for a request
func NewRetrieveAddonParamsWithContext(ctx context.Context) *RetrieveAddonParams {
	var ()
	return &RetrieveAddonParams{

		Context: ctx,
	}
}

// NewRetrieveAddonParamsWithHTTPClient creates a new RetrieveAddonParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRetrieveAddonParamsWithHTTPClient(client *http.Client) *RetrieveAddonParams {
	var ()
	return &RetrieveAddonParams{
		HTTPClient: client,
	}
}

/*RetrieveAddonParams contains all the parameters to send to the API endpoint
for the retrieve addon operation typically these are written to a http.Request
*/
type RetrieveAddonParams struct {

	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the retrieve addon params
func (o *RetrieveAddonParams) WithTimeout(timeout time.Duration) *RetrieveAddonParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve addon params
func (o *RetrieveAddonParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve addon params
func (o *RetrieveAddonParams) WithContext(ctx context.Context) *RetrieveAddonParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve addon params
func (o *RetrieveAddonParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve addon params
func (o *RetrieveAddonParams) WithHTTPClient(client *http.Client) *RetrieveAddonParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve addon params
func (o *RetrieveAddonParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the retrieve addon params
func (o *RetrieveAddonParams) WithID(id string) *RetrieveAddonParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the retrieve addon params
func (o *RetrieveAddonParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveAddonParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
