// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/markns/chargebee-golang/models"
)

// RetrieveAddonReader is a Reader for the RetrieveAddon structure.
type RetrieveAddonReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RetrieveAddonReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewRetrieveAddonOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRetrieveAddonOK creates a RetrieveAddonOK with default headers values
func NewRetrieveAddonOK() *RetrieveAddonOK {
	return &RetrieveAddonOK{}
}

/*RetrieveAddonOK handles this case with default header values.

retrieveAddon response
*/
type RetrieveAddonOK struct {
	Payload *models.AddonResponse
}

func (o *RetrieveAddonOK) Error() string {
	return fmt.Sprintf("[GET /addons/{id}][%d] retrieveAddonOK  %+v", 200, o.Payload)
}

func (o *RetrieveAddonOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.AddonResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
