// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// NewRetrieveLatestResourceMigrationParams creates a new RetrieveLatestResourceMigrationParams object
// with the default values initialized.
func NewRetrieveLatestResourceMigrationParams() *RetrieveLatestResourceMigrationParams {
	var ()
	return &RetrieveLatestResourceMigrationParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewRetrieveLatestResourceMigrationParamsWithTimeout creates a new RetrieveLatestResourceMigrationParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewRetrieveLatestResourceMigrationParamsWithTimeout(timeout time.Duration) *RetrieveLatestResourceMigrationParams {
	var ()
	return &RetrieveLatestResourceMigrationParams{

		timeout: timeout,
	}
}

// NewRetrieveLatestResourceMigrationParamsWithContext creates a new RetrieveLatestResourceMigrationParams object
// with the default values initialized, and the ability to set a context for a request
func NewRetrieveLatestResourceMigrationParamsWithContext(ctx context.Context) *RetrieveLatestResourceMigrationParams {
	var ()
	return &RetrieveLatestResourceMigrationParams{

		Context: ctx,
	}
}

// NewRetrieveLatestResourceMigrationParamsWithHTTPClient creates a new RetrieveLatestResourceMigrationParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewRetrieveLatestResourceMigrationParamsWithHTTPClient(client *http.Client) *RetrieveLatestResourceMigrationParams {
	var ()
	return &RetrieveLatestResourceMigrationParams{
		HTTPClient: client,
	}
}

/*RetrieveLatestResourceMigrationParams contains all the parameters to send to the API endpoint
for the retrieve latest resource migration operation typically these are written to a http.Request
*/
type RetrieveLatestResourceMigrationParams struct {

	/*ResourceMigrationRetrieveLatestRequest*/
	ResourceMigrationRetrieveLatestRequest *models.ResourceMigrationRetrieveLatestRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the retrieve latest resource migration params
func (o *RetrieveLatestResourceMigrationParams) WithTimeout(timeout time.Duration) *RetrieveLatestResourceMigrationParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the retrieve latest resource migration params
func (o *RetrieveLatestResourceMigrationParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the retrieve latest resource migration params
func (o *RetrieveLatestResourceMigrationParams) WithContext(ctx context.Context) *RetrieveLatestResourceMigrationParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the retrieve latest resource migration params
func (o *RetrieveLatestResourceMigrationParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the retrieve latest resource migration params
func (o *RetrieveLatestResourceMigrationParams) WithHTTPClient(client *http.Client) *RetrieveLatestResourceMigrationParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the retrieve latest resource migration params
func (o *RetrieveLatestResourceMigrationParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithResourceMigrationRetrieveLatestRequest adds the resourceMigrationRetrieveLatestRequest to the retrieve latest resource migration params
func (o *RetrieveLatestResourceMigrationParams) WithResourceMigrationRetrieveLatestRequest(resourceMigrationRetrieveLatestRequest *models.ResourceMigrationRetrieveLatestRequest) *RetrieveLatestResourceMigrationParams {
	o.SetResourceMigrationRetrieveLatestRequest(resourceMigrationRetrieveLatestRequest)
	return o
}

// SetResourceMigrationRetrieveLatestRequest adds the resourceMigrationRetrieveLatestRequest to the retrieve latest resource migration params
func (o *RetrieveLatestResourceMigrationParams) SetResourceMigrationRetrieveLatestRequest(resourceMigrationRetrieveLatestRequest *models.ResourceMigrationRetrieveLatestRequest) {
	o.ResourceMigrationRetrieveLatestRequest = resourceMigrationRetrieveLatestRequest
}

// WriteToRequest writes these params to a swagger request
func (o *RetrieveLatestResourceMigrationParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ResourceMigrationRetrieveLatestRequest != nil {
		if err := r.SetBodyParam(o.ResourceMigrationRetrieveLatestRequest); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
