// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/markns/chargebee-golang/models"
)

// NewSwitchGatewayForCustomerCardParams creates a new SwitchGatewayForCustomerCardParams object
// with the default values initialized.
func NewSwitchGatewayForCustomerCardParams() *SwitchGatewayForCustomerCardParams {
	var ()
	return &SwitchGatewayForCustomerCardParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSwitchGatewayForCustomerCardParamsWithTimeout creates a new SwitchGatewayForCustomerCardParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSwitchGatewayForCustomerCardParamsWithTimeout(timeout time.Duration) *SwitchGatewayForCustomerCardParams {
	var ()
	return &SwitchGatewayForCustomerCardParams{

		timeout: timeout,
	}
}

// NewSwitchGatewayForCustomerCardParamsWithContext creates a new SwitchGatewayForCustomerCardParams object
// with the default values initialized, and the ability to set a context for a request
func NewSwitchGatewayForCustomerCardParamsWithContext(ctx context.Context) *SwitchGatewayForCustomerCardParams {
	var ()
	return &SwitchGatewayForCustomerCardParams{

		Context: ctx,
	}
}

// NewSwitchGatewayForCustomerCardParamsWithHTTPClient creates a new SwitchGatewayForCustomerCardParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewSwitchGatewayForCustomerCardParamsWithHTTPClient(client *http.Client) *SwitchGatewayForCustomerCardParams {
	var ()
	return &SwitchGatewayForCustomerCardParams{
		HTTPClient: client,
	}
}

/*SwitchGatewayForCustomerCardParams contains all the parameters to send to the API endpoint
for the switch gateway for customer card operation typically these are written to a http.Request
*/
type SwitchGatewayForCustomerCardParams struct {

	/*CardSwitchGatewayForCustomerRequest*/
	CardSwitchGatewayForCustomerRequest *models.CardSwitchGatewayForCustomerRequest
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the switch gateway for customer card params
func (o *SwitchGatewayForCustomerCardParams) WithTimeout(timeout time.Duration) *SwitchGatewayForCustomerCardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the switch gateway for customer card params
func (o *SwitchGatewayForCustomerCardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the switch gateway for customer card params
func (o *SwitchGatewayForCustomerCardParams) WithContext(ctx context.Context) *SwitchGatewayForCustomerCardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the switch gateway for customer card params
func (o *SwitchGatewayForCustomerCardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the switch gateway for customer card params
func (o *SwitchGatewayForCustomerCardParams) WithHTTPClient(client *http.Client) *SwitchGatewayForCustomerCardParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the switch gateway for customer card params
func (o *SwitchGatewayForCustomerCardParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCardSwitchGatewayForCustomerRequest adds the cardSwitchGatewayForCustomerRequest to the switch gateway for customer card params
func (o *SwitchGatewayForCustomerCardParams) WithCardSwitchGatewayForCustomerRequest(cardSwitchGatewayForCustomerRequest *models.CardSwitchGatewayForCustomerRequest) *SwitchGatewayForCustomerCardParams {
	o.SetCardSwitchGatewayForCustomerRequest(cardSwitchGatewayForCustomerRequest)
	return o
}

// SetCardSwitchGatewayForCustomerRequest adds the cardSwitchGatewayForCustomerRequest to the switch gateway for customer card params
func (o *SwitchGatewayForCustomerCardParams) SetCardSwitchGatewayForCustomerRequest(cardSwitchGatewayForCustomerRequest *models.CardSwitchGatewayForCustomerRequest) {
	o.CardSwitchGatewayForCustomerRequest = cardSwitchGatewayForCustomerRequest
}

// WithID adds the id to the switch gateway for customer card params
func (o *SwitchGatewayForCustomerCardParams) WithID(id string) *SwitchGatewayForCustomerCardParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the switch gateway for customer card params
func (o *SwitchGatewayForCustomerCardParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *SwitchGatewayForCustomerCardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CardSwitchGatewayForCustomerRequest == nil {
		o.CardSwitchGatewayForCustomerRequest = new(models.CardSwitchGatewayForCustomerRequest)
	}

	if err := r.SetBodyParam(o.CardSwitchGatewayForCustomerRequest); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
