// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// TravelForwardTimeMachineReader is a Reader for the TravelForwardTimeMachine structure.
type TravelForwardTimeMachineReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TravelForwardTimeMachineReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewTravelForwardTimeMachineOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTravelForwardTimeMachineOK creates a TravelForwardTimeMachineOK with default headers values
func NewTravelForwardTimeMachineOK() *TravelForwardTimeMachineOK {
	return &TravelForwardTimeMachineOK{}
}

/*TravelForwardTimeMachineOK handles this case with default header values.

travelForwardTimeMachine response
*/
type TravelForwardTimeMachineOK struct {
	Payload *models.TimeMachineResponse
}

func (o *TravelForwardTimeMachineOK) Error() string {
	return fmt.Sprintf("[POST /time_machines/{id}/travel_forward][%d] travelForwardTimeMachineOK  %+v", 200, o.Payload)
}

func (o *TravelForwardTimeMachineOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.TimeMachineResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
