// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/markns/chargebee-golang/models"
)

// UpcomingInvoicesEstimateEstimateReader is a Reader for the UpcomingInvoicesEstimateEstimate structure.
type UpcomingInvoicesEstimateEstimateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpcomingInvoicesEstimateEstimateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpcomingInvoicesEstimateEstimateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpcomingInvoicesEstimateEstimateOK creates a UpcomingInvoicesEstimateEstimateOK with default headers values
func NewUpcomingInvoicesEstimateEstimateOK() *UpcomingInvoicesEstimateEstimateOK {
	return &UpcomingInvoicesEstimateEstimateOK{}
}

/*UpcomingInvoicesEstimateEstimateOK handles this case with default header values.

upcomingInvoicesEstimateEstimate response
*/
type UpcomingInvoicesEstimateEstimateOK struct {
	Payload *models.Estimate
}

func (o *UpcomingInvoicesEstimateEstimateOK) Error() string {
	return fmt.Sprintf("[GET /customers/{id}/upcoming_invoices_estimate][%d] upcomingInvoicesEstimateEstimateOK  %+v", 200, o.Payload)
}

func (o *UpcomingInvoicesEstimateEstimateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Estimate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
