// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/markns/chargebee-golang/models"
)

// NewUpdatePaymentMethodHostedPageParams creates a new UpdatePaymentMethodHostedPageParams object
// with the default values initialized.
func NewUpdatePaymentMethodHostedPageParams() *UpdatePaymentMethodHostedPageParams {
	var ()
	return &UpdatePaymentMethodHostedPageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdatePaymentMethodHostedPageParamsWithTimeout creates a new UpdatePaymentMethodHostedPageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdatePaymentMethodHostedPageParamsWithTimeout(timeout time.Duration) *UpdatePaymentMethodHostedPageParams {
	var ()
	return &UpdatePaymentMethodHostedPageParams{

		timeout: timeout,
	}
}

// NewUpdatePaymentMethodHostedPageParamsWithContext creates a new UpdatePaymentMethodHostedPageParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdatePaymentMethodHostedPageParamsWithContext(ctx context.Context) *UpdatePaymentMethodHostedPageParams {
	var ()
	return &UpdatePaymentMethodHostedPageParams{

		Context: ctx,
	}
}

// NewUpdatePaymentMethodHostedPageParamsWithHTTPClient creates a new UpdatePaymentMethodHostedPageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdatePaymentMethodHostedPageParamsWithHTTPClient(client *http.Client) *UpdatePaymentMethodHostedPageParams {
	var ()
	return &UpdatePaymentMethodHostedPageParams{
		HTTPClient: client,
	}
}

/*UpdatePaymentMethodHostedPageParams contains all the parameters to send to the API endpoint
for the update payment method hosted page operation typically these are written to a http.Request
*/
type UpdatePaymentMethodHostedPageParams struct {

	/*HostedPageUpdatePaymentMethodRequest*/
	HostedPageUpdatePaymentMethodRequest *models.HostedPageUpdatePaymentMethodRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update payment method hosted page params
func (o *UpdatePaymentMethodHostedPageParams) WithTimeout(timeout time.Duration) *UpdatePaymentMethodHostedPageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update payment method hosted page params
func (o *UpdatePaymentMethodHostedPageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update payment method hosted page params
func (o *UpdatePaymentMethodHostedPageParams) WithContext(ctx context.Context) *UpdatePaymentMethodHostedPageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update payment method hosted page params
func (o *UpdatePaymentMethodHostedPageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update payment method hosted page params
func (o *UpdatePaymentMethodHostedPageParams) WithHTTPClient(client *http.Client) *UpdatePaymentMethodHostedPageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update payment method hosted page params
func (o *UpdatePaymentMethodHostedPageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHostedPageUpdatePaymentMethodRequest adds the hostedPageUpdatePaymentMethodRequest to the update payment method hosted page params
func (o *UpdatePaymentMethodHostedPageParams) WithHostedPageUpdatePaymentMethodRequest(hostedPageUpdatePaymentMethodRequest *models.HostedPageUpdatePaymentMethodRequest) *UpdatePaymentMethodHostedPageParams {
	o.SetHostedPageUpdatePaymentMethodRequest(hostedPageUpdatePaymentMethodRequest)
	return o
}

// SetHostedPageUpdatePaymentMethodRequest adds the hostedPageUpdatePaymentMethodRequest to the update payment method hosted page params
func (o *UpdatePaymentMethodHostedPageParams) SetHostedPageUpdatePaymentMethodRequest(hostedPageUpdatePaymentMethodRequest *models.HostedPageUpdatePaymentMethodRequest) {
	o.HostedPageUpdatePaymentMethodRequest = hostedPageUpdatePaymentMethodRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdatePaymentMethodHostedPageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.HostedPageUpdatePaymentMethodRequest == nil {
		o.HostedPageUpdatePaymentMethodRequest = new(models.HostedPageUpdatePaymentMethodRequest)
	}

	if err := r.SetBodyParam(o.HostedPageUpdatePaymentMethodRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
