// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// NewUpdateCardPaymentSourceParams creates a new UpdateCardPaymentSourceParams object
// with the default values initialized.
func NewUpdateCardPaymentSourceParams() *UpdateCardPaymentSourceParams {
	var ()
	return &UpdateCardPaymentSourceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCardPaymentSourceParamsWithTimeout creates a new UpdateCardPaymentSourceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCardPaymentSourceParamsWithTimeout(timeout time.Duration) *UpdateCardPaymentSourceParams {
	var ()
	return &UpdateCardPaymentSourceParams{

		timeout: timeout,
	}
}

// NewUpdateCardPaymentSourceParamsWithContext creates a new UpdateCardPaymentSourceParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCardPaymentSourceParamsWithContext(ctx context.Context) *UpdateCardPaymentSourceParams {
	var ()
	return &UpdateCardPaymentSourceParams{

		Context: ctx,
	}
}

// NewUpdateCardPaymentSourceParamsWithHTTPClient creates a new UpdateCardPaymentSourceParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCardPaymentSourceParamsWithHTTPClient(client *http.Client) *UpdateCardPaymentSourceParams {
	var ()
	return &UpdateCardPaymentSourceParams{
		HTTPClient: client,
	}
}

/*UpdateCardPaymentSourceParams contains all the parameters to send to the API endpoint
for the update card payment source operation typically these are written to a http.Request
*/
type UpdateCardPaymentSourceParams struct {

	/*PaymentSourceUpdateCardRequest*/
	PaymentSourceUpdateCardRequest *models.PaymentSourceUpdateCardRequest
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update card payment source params
func (o *UpdateCardPaymentSourceParams) WithTimeout(timeout time.Duration) *UpdateCardPaymentSourceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update card payment source params
func (o *UpdateCardPaymentSourceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update card payment source params
func (o *UpdateCardPaymentSourceParams) WithContext(ctx context.Context) *UpdateCardPaymentSourceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update card payment source params
func (o *UpdateCardPaymentSourceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update card payment source params
func (o *UpdateCardPaymentSourceParams) WithHTTPClient(client *http.Client) *UpdateCardPaymentSourceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update card payment source params
func (o *UpdateCardPaymentSourceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithPaymentSourceUpdateCardRequest adds the paymentSourceUpdateCardRequest to the update card payment source params
func (o *UpdateCardPaymentSourceParams) WithPaymentSourceUpdateCardRequest(paymentSourceUpdateCardRequest *models.PaymentSourceUpdateCardRequest) *UpdateCardPaymentSourceParams {
	o.SetPaymentSourceUpdateCardRequest(paymentSourceUpdateCardRequest)
	return o
}

// SetPaymentSourceUpdateCardRequest adds the paymentSourceUpdateCardRequest to the update card payment source params
func (o *UpdateCardPaymentSourceParams) SetPaymentSourceUpdateCardRequest(paymentSourceUpdateCardRequest *models.PaymentSourceUpdateCardRequest) {
	o.PaymentSourceUpdateCardRequest = paymentSourceUpdateCardRequest
}

// WithID adds the id to the update card payment source params
func (o *UpdateCardPaymentSourceParams) WithID(id string) *UpdateCardPaymentSourceParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update card payment source params
func (o *UpdateCardPaymentSourceParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCardPaymentSourceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.PaymentSourceUpdateCardRequest != nil {
		if err := r.SetBodyParam(o.PaymentSourceUpdateCardRequest); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
