// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/markns/chargebee-golang/models"
)

// NewUpdateCardHostedPageParams creates a new UpdateCardHostedPageParams object
// with the default values initialized.
func NewUpdateCardHostedPageParams() *UpdateCardHostedPageParams {
	var ()
	return &UpdateCardHostedPageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateCardHostedPageParamsWithTimeout creates a new UpdateCardHostedPageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateCardHostedPageParamsWithTimeout(timeout time.Duration) *UpdateCardHostedPageParams {
	var ()
	return &UpdateCardHostedPageParams{

		timeout: timeout,
	}
}

// NewUpdateCardHostedPageParamsWithContext creates a new UpdateCardHostedPageParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateCardHostedPageParamsWithContext(ctx context.Context) *UpdateCardHostedPageParams {
	var ()
	return &UpdateCardHostedPageParams{

		Context: ctx,
	}
}

// NewUpdateCardHostedPageParamsWithHTTPClient creates a new UpdateCardHostedPageParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateCardHostedPageParamsWithHTTPClient(client *http.Client) *UpdateCardHostedPageParams {
	var ()
	return &UpdateCardHostedPageParams{
		HTTPClient: client,
	}
}

/*UpdateCardHostedPageParams contains all the parameters to send to the API endpoint
for the update card hosted page operation typically these are written to a http.Request
*/
type UpdateCardHostedPageParams struct {

	/*HostedPageUpdateCardRequest*/
	HostedPageUpdateCardRequest *models.HostedPageUpdateCardRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update card hosted page params
func (o *UpdateCardHostedPageParams) WithTimeout(timeout time.Duration) *UpdateCardHostedPageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update card hosted page params
func (o *UpdateCardHostedPageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update card hosted page params
func (o *UpdateCardHostedPageParams) WithContext(ctx context.Context) *UpdateCardHostedPageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update card hosted page params
func (o *UpdateCardHostedPageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update card hosted page params
func (o *UpdateCardHostedPageParams) WithHTTPClient(client *http.Client) *UpdateCardHostedPageParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update card hosted page params
func (o *UpdateCardHostedPageParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithHostedPageUpdateCardRequest adds the hostedPageUpdateCardRequest to the update card hosted page params
func (o *UpdateCardHostedPageParams) WithHostedPageUpdateCardRequest(hostedPageUpdateCardRequest *models.HostedPageUpdateCardRequest) *UpdateCardHostedPageParams {
	o.SetHostedPageUpdateCardRequest(hostedPageUpdateCardRequest)
	return o
}

// SetHostedPageUpdateCardRequest adds the hostedPageUpdateCardRequest to the update card hosted page params
func (o *UpdateCardHostedPageParams) SetHostedPageUpdateCardRequest(hostedPageUpdateCardRequest *models.HostedPageUpdateCardRequest) {
	o.HostedPageUpdateCardRequest = hostedPageUpdateCardRequest
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateCardHostedPageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.HostedPageUpdateCardRequest == nil {
		o.HostedPageUpdateCardRequest = new(models.HostedPageUpdateCardRequest)
	}

	if err := r.SetBodyParam(o.HostedPageUpdateCardRequest); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
