// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// UpdateSubscriptionEstimateReader is a Reader for the UpdateSubscriptionEstimate structure.
type UpdateSubscriptionEstimateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UpdateSubscriptionEstimateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUpdateSubscriptionEstimateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUpdateSubscriptionEstimateOK creates a UpdateSubscriptionEstimateOK with default headers values
func NewUpdateSubscriptionEstimateOK() *UpdateSubscriptionEstimateOK {
	return &UpdateSubscriptionEstimateOK{}
}

/*UpdateSubscriptionEstimateOK handles this case with default header values.

updateSubscriptionEstimate response
*/
type UpdateSubscriptionEstimateOK struct {
	Payload *models.EstimateResponse
}

func (o *UpdateSubscriptionEstimateOK) Error() string {
	return fmt.Sprintf("[POST /estimates/update_subscription][%d] updateSubscriptionEstimateOK  %+v", 200, o.Payload)
}

func (o *UpdateSubscriptionEstimateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.EstimateResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
