// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/markns/chargebee-golang/models"
)

// NewUpdateBillingInfoCustomerParams creates a new UpdateBillingInfoCustomerParams object
// with the default values initialized.
func NewUpdateBillingInfoCustomerParams() *UpdateBillingInfoCustomerParams {
	var ()
	return &UpdateBillingInfoCustomerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUpdateBillingInfoCustomerParamsWithTimeout creates a new UpdateBillingInfoCustomerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUpdateBillingInfoCustomerParamsWithTimeout(timeout time.Duration) *UpdateBillingInfoCustomerParams {
	var ()
	return &UpdateBillingInfoCustomerParams{

		timeout: timeout,
	}
}

// NewUpdateBillingInfoCustomerParamsWithContext creates a new UpdateBillingInfoCustomerParams object
// with the default values initialized, and the ability to set a context for a request
func NewUpdateBillingInfoCustomerParamsWithContext(ctx context.Context) *UpdateBillingInfoCustomerParams {
	var ()
	return &UpdateBillingInfoCustomerParams{

		Context: ctx,
	}
}

// NewUpdateBillingInfoCustomerParamsWithHTTPClient creates a new UpdateBillingInfoCustomerParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewUpdateBillingInfoCustomerParamsWithHTTPClient(client *http.Client) *UpdateBillingInfoCustomerParams {
	var ()
	return &UpdateBillingInfoCustomerParams{
		HTTPClient: client,
	}
}

/*UpdateBillingInfoCustomerParams contains all the parameters to send to the API endpoint
for the update billing info customer operation typically these are written to a http.Request
*/
type UpdateBillingInfoCustomerParams struct {

	/*CustomerUpdateBillingInfoRequest*/
	CustomerUpdateBillingInfoRequest *models.CustomerUpdateBillingInfoRequest
	/*ID*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the update billing info customer params
func (o *UpdateBillingInfoCustomerParams) WithTimeout(timeout time.Duration) *UpdateBillingInfoCustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the update billing info customer params
func (o *UpdateBillingInfoCustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the update billing info customer params
func (o *UpdateBillingInfoCustomerParams) WithContext(ctx context.Context) *UpdateBillingInfoCustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the update billing info customer params
func (o *UpdateBillingInfoCustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the update billing info customer params
func (o *UpdateBillingInfoCustomerParams) WithHTTPClient(client *http.Client) *UpdateBillingInfoCustomerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the update billing info customer params
func (o *UpdateBillingInfoCustomerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithCustomerUpdateBillingInfoRequest adds the customerUpdateBillingInfoRequest to the update billing info customer params
func (o *UpdateBillingInfoCustomerParams) WithCustomerUpdateBillingInfoRequest(customerUpdateBillingInfoRequest *models.CustomerUpdateBillingInfoRequest) *UpdateBillingInfoCustomerParams {
	o.SetCustomerUpdateBillingInfoRequest(customerUpdateBillingInfoRequest)
	return o
}

// SetCustomerUpdateBillingInfoRequest adds the customerUpdateBillingInfoRequest to the update billing info customer params
func (o *UpdateBillingInfoCustomerParams) SetCustomerUpdateBillingInfoRequest(customerUpdateBillingInfoRequest *models.CustomerUpdateBillingInfoRequest) {
	o.CustomerUpdateBillingInfoRequest = customerUpdateBillingInfoRequest
}

// WithID adds the id to the update billing info customer params
func (o *UpdateBillingInfoCustomerParams) WithID(id string) *UpdateBillingInfoCustomerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the update billing info customer params
func (o *UpdateBillingInfoCustomerParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *UpdateBillingInfoCustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.CustomerUpdateBillingInfoRequest != nil {
		if err := r.SetBodyParam(o.CustomerUpdateBillingInfoRequest); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
