// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Address address
// swagger:model Address
type Address struct {

	// addr
	Addr string `json:"addr,omitempty"`

	// city
	City string `json:"city,omitempty"`

	// company
	Company string `json:"company,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// email
	Email string `json:"email,omitempty"`

	// extended addr
	ExtendedAddr string `json:"extended_addr,omitempty"`

	// extended addr2
	ExtendedAddr2 string `json:"extended_addr2,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// label
	Label string `json:"label,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// phone
	Phone string `json:"phone,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// state code
	StateCode string `json:"state_code,omitempty"`

	// subscription id
	SubscriptionID string `json:"subscription_id,omitempty"`

	// validation status
	ValidationStatus string `json:"validation_status,omitempty"`

	// zip
	Zip string `json:"zip,omitempty"`
}

// Validate validates this address
func (m *Address) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateValidationStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var addressTypeValidationStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["not_validated","valid","partially_valid","invalid"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		addressTypeValidationStatusPropEnum = append(addressTypeValidationStatusPropEnum, v)
	}
}

const (

	// AddressValidationStatusNotValidated captures enum value "not_validated"
	AddressValidationStatusNotValidated string = "not_validated"

	// AddressValidationStatusValid captures enum value "valid"
	AddressValidationStatusValid string = "valid"

	// AddressValidationStatusPartiallyValid captures enum value "partially_valid"
	AddressValidationStatusPartiallyValid string = "partially_valid"

	// AddressValidationStatusInvalid captures enum value "invalid"
	AddressValidationStatusInvalid string = "invalid"
)

// prop value enum
func (m *Address) validateValidationStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, addressTypeValidationStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *Address) validateValidationStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.ValidationStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateValidationStatusEnum("validation_status", "body", m.ValidationStatus); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Address) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Address) UnmarshalBinary(b []byte) error {
	var res Address
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
