// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CardCopyCardForCustomerRequest card copy card for customer request
// swagger:model CardCopyCardForCustomerRequest
type CardCopyCardForCustomerRequest struct {

	// gateway account id
	GatewayAccountID string `json:"gateway_account_id,omitempty"`
}

// Validate validates this card copy card for customer request
func (m *CardCopyCardForCustomerRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *CardCopyCardForCustomerRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CardCopyCardForCustomerRequest) UnmarshalBinary(b []byte) error {
	var res CardCopyCardForCustomerRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
