// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Contact contact
// swagger:model Contact

type Contact struct {

	// email
	Email string `json:"email,omitempty"`

	// enabled
	Enabled bool `json:"enabled,omitempty"`

	// first name
	FirstName string `json:"first_name,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// label
	Label string `json:"label,omitempty"`

	// last name
	LastName string `json:"last_name,omitempty"`

	// phone
	Phone string `json:"phone,omitempty"`

	// send account email
	SendAccountEmail bool `json:"send_account_email,omitempty"`

	// send billing email
	SendBillingEmail bool `json:"send_billing_email,omitempty"`
}

/* polymorph Contact email false */

/* polymorph Contact enabled false */

/* polymorph Contact first_name false */

/* polymorph Contact id false */

/* polymorph Contact label false */

/* polymorph Contact last_name false */

/* polymorph Contact phone false */

/* polymorph Contact send_account_email false */

/* polymorph Contact send_billing_email false */

// Validate validates this contact
func (m *Contact) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Contact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Contact) UnmarshalBinary(b []byte) error {
	var res Contact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
