// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CouponCode coupon code
// swagger:model CouponCode

type CouponCode struct {

	// code
	Code string `json:"code,omitempty"`

	// coupon id
	CouponID string `json:"coupon_id,omitempty"`

	// coupon set id
	CouponSetID string `json:"coupon_set_id,omitempty"`

	// coupon set name
	CouponSetName string `json:"coupon_set_name,omitempty"`

	// status
	Status string `json:"status,omitempty"`
}

/* polymorph CouponCode code false */

/* polymorph CouponCode coupon_id false */

/* polymorph CouponCode coupon_set_id false */

/* polymorph CouponCode coupon_set_name false */

/* polymorph CouponCode status false */

// Validate validates this coupon code
func (m *CouponCode) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var couponCodeTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["in_progress","success","voided","failure","timeout","needs_attention"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		couponCodeTypeStatusPropEnum = append(couponCodeTypeStatusPropEnum, v)
	}
}

const (
	// CouponCodeStatusInProgress captures enum value "in_progress"
	CouponCodeStatusInProgress string = "in_progress"
	// CouponCodeStatusSuccess captures enum value "success"
	CouponCodeStatusSuccess string = "success"
	// CouponCodeStatusVoided captures enum value "voided"
	CouponCodeStatusVoided string = "voided"
	// CouponCodeStatusFailure captures enum value "failure"
	CouponCodeStatusFailure string = "failure"
	// CouponCodeStatusTimeout captures enum value "timeout"
	CouponCodeStatusTimeout string = "timeout"
	// CouponCodeStatusNeedsAttention captures enum value "needs_attention"
	CouponCodeStatusNeedsAttention string = "needs_attention"
)

// prop value enum
func (m *CouponCode) validateStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, couponCodeTypeStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CouponCode) validateStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.Status) { // not required
		return nil
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", m.Status); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CouponCode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CouponCode) UnmarshalBinary(b []byte) error {
	var res CouponCode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
