// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// CouponSetUpdateRequest coupon set update request
// swagger:model CouponSetUpdateRequest

type CouponSetUpdateRequest struct {

	// meta data
	MetaData string `json:"meta_data,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

/* polymorph CouponSetUpdateRequest meta_data false */

/* polymorph CouponSetUpdateRequest name false */

// Validate validates this coupon set update request
func (m *CouponSetUpdateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *CouponSetUpdateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CouponSetUpdateRequest) UnmarshalBinary(b []byte) error {
	var res CouponSetUpdateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
