// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CustomerRecordExcessPaymentRequest customer record excess payment request
// swagger:model CustomerRecordExcessPaymentRequest

type CustomerRecordExcessPaymentRequest struct {

	// comment
	Comment string `json:"comment,omitempty"`

	// transaction amount
	TransactionAmount int32 `json:"transaction[amount],omitempty"`

	// transaction currency code
	TransactionCurrencyCode string `json:"transaction[currency_code],omitempty"`

	// transaction date
	TransactionDate int64 `json:"transaction[date],omitempty"`

	// transaction payment method
	TransactionPaymentMethod string `json:"transaction[payment_method],omitempty"`

	// transaction reference number
	TransactionReferenceNumber string `json:"transaction[reference_number],omitempty"`
}

/* polymorph CustomerRecordExcessPaymentRequest comment false */

/* polymorph CustomerRecordExcessPaymentRequest transaction[amount] false */

/* polymorph CustomerRecordExcessPaymentRequest transaction[currency_code] false */

/* polymorph CustomerRecordExcessPaymentRequest transaction[date] false */

/* polymorph CustomerRecordExcessPaymentRequest transaction[payment_method] false */

/* polymorph CustomerRecordExcessPaymentRequest transaction[reference_number] false */

// Validate validates this customer record excess payment request
func (m *CustomerRecordExcessPaymentRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTransactionPaymentMethod(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var customerRecordExcessPaymentRequestTypeTransactionPaymentMethodPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["card","cash","check","chargeback","bank_transfer","amazon_payments","paypal_express_checkout","direct_debit","alipay","unionpay","apple_pay","other"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		customerRecordExcessPaymentRequestTypeTransactionPaymentMethodPropEnum = append(customerRecordExcessPaymentRequestTypeTransactionPaymentMethodPropEnum, v)
	}
}

const (
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodCard captures enum value "card"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodCard string = "card"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodCash captures enum value "cash"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodCash string = "cash"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodCheck captures enum value "check"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodCheck string = "check"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodChargeback captures enum value "chargeback"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodChargeback string = "chargeback"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodBankTransfer captures enum value "bank_transfer"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodBankTransfer string = "bank_transfer"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodAmazonPayments captures enum value "amazon_payments"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodAmazonPayments string = "amazon_payments"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodPaypalExpressCheckout captures enum value "paypal_express_checkout"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodPaypalExpressCheckout string = "paypal_express_checkout"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodDirectDebit captures enum value "direct_debit"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodDirectDebit string = "direct_debit"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodAlipay captures enum value "alipay"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodAlipay string = "alipay"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodUnionpay captures enum value "unionpay"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodUnionpay string = "unionpay"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodApplePay captures enum value "apple_pay"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodApplePay string = "apple_pay"
	// CustomerRecordExcessPaymentRequestTransactionPaymentMethodOther captures enum value "other"
	CustomerRecordExcessPaymentRequestTransactionPaymentMethodOther string = "other"
)

// prop value enum
func (m *CustomerRecordExcessPaymentRequest) validateTransactionPaymentMethodEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, customerRecordExcessPaymentRequestTypeTransactionPaymentMethodPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *CustomerRecordExcessPaymentRequest) validateTransactionPaymentMethod(formats strfmt.Registry) error {

	if swag.IsZero(m.TransactionPaymentMethod) { // not required
		return nil
	}

	// value enum
	if err := m.validateTransactionPaymentMethodEnum("transaction[payment_method]", "body", m.TransactionPaymentMethod); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *CustomerRecordExcessPaymentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CustomerRecordExcessPaymentRequest) UnmarshalBinary(b []byte) error {
	var res CustomerRecordExcessPaymentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
