// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HostedPageUpdateCardRequest hosted page update card request
// swagger:model HostedPageUpdateCardRequest

type HostedPageUpdateCardRequest struct {

	// cancel url
	CancelURL string `json:"cancel_url,omitempty"`

	// card gateway
	CardGateway string `json:"card[gateway],omitempty"`

	// card gateway account id
	CardGatewayAccountID string `json:"card[gateway_account_id],omitempty"`

	// customer id
	CustomerID string `json:"customer[id],omitempty"`

	// customer vat number
	CustomerVatNumber string `json:"customer[vat_number],omitempty"`

	// embed
	Embed bool `json:"embed,omitempty"`

	// iframe messaging
	IframeMessaging bool `json:"iframe_messaging,omitempty"`

	// pass thru content
	PassThruContent string `json:"pass_thru_content,omitempty"`

	// redirect url
	RedirectURL string `json:"redirect_url,omitempty"`
}

/* polymorph HostedPageUpdateCardRequest cancel_url false */

/* polymorph HostedPageUpdateCardRequest card[gateway] false */

/* polymorph HostedPageUpdateCardRequest card[gateway_account_id] false */

/* polymorph HostedPageUpdateCardRequest customer[id] false */

/* polymorph HostedPageUpdateCardRequest customer[vat_number] false */

/* polymorph HostedPageUpdateCardRequest embed false */

/* polymorph HostedPageUpdateCardRequest iframe_messaging false */

/* polymorph HostedPageUpdateCardRequest pass_thru_content false */

/* polymorph HostedPageUpdateCardRequest redirect_url false */

// Validate validates this hosted page update card request
func (m *HostedPageUpdateCardRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCardGateway(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var hostedPageUpdateCardRequestTypeCardGatewayPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["chargebee","stripe","wepay","braintree","authorize_net","paypal_pro","pin","eway","eway_rapid","worldpay","balanced_payments","beanstream","bluepay","elavon","first_data_global","hdfc","migs","nmi","ogone","paymill","paypal_payflow_pro","sage_pay","tco","wirecard","amazon_payments","paypal_express_checkout","gocardless","adyen","orbital","moneris_us","moneris","not_applicable"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hostedPageUpdateCardRequestTypeCardGatewayPropEnum = append(hostedPageUpdateCardRequestTypeCardGatewayPropEnum, v)
	}
}

const (
	// HostedPageUpdateCardRequestCardGatewayChargebee captures enum value "chargebee"
	HostedPageUpdateCardRequestCardGatewayChargebee string = "chargebee"
	// HostedPageUpdateCardRequestCardGatewayStripe captures enum value "stripe"
	HostedPageUpdateCardRequestCardGatewayStripe string = "stripe"
	// HostedPageUpdateCardRequestCardGatewayWepay captures enum value "wepay"
	HostedPageUpdateCardRequestCardGatewayWepay string = "wepay"
	// HostedPageUpdateCardRequestCardGatewayBraintree captures enum value "braintree"
	HostedPageUpdateCardRequestCardGatewayBraintree string = "braintree"
	// HostedPageUpdateCardRequestCardGatewayAuthorizeNet captures enum value "authorize_net"
	HostedPageUpdateCardRequestCardGatewayAuthorizeNet string = "authorize_net"
	// HostedPageUpdateCardRequestCardGatewayPaypalPro captures enum value "paypal_pro"
	HostedPageUpdateCardRequestCardGatewayPaypalPro string = "paypal_pro"
	// HostedPageUpdateCardRequestCardGatewayPin captures enum value "pin"
	HostedPageUpdateCardRequestCardGatewayPin string = "pin"
	// HostedPageUpdateCardRequestCardGatewayEway captures enum value "eway"
	HostedPageUpdateCardRequestCardGatewayEway string = "eway"
	// HostedPageUpdateCardRequestCardGatewayEwayRapid captures enum value "eway_rapid"
	HostedPageUpdateCardRequestCardGatewayEwayRapid string = "eway_rapid"
	// HostedPageUpdateCardRequestCardGatewayWorldpay captures enum value "worldpay"
	HostedPageUpdateCardRequestCardGatewayWorldpay string = "worldpay"
	// HostedPageUpdateCardRequestCardGatewayBalancedPayments captures enum value "balanced_payments"
	HostedPageUpdateCardRequestCardGatewayBalancedPayments string = "balanced_payments"
	// HostedPageUpdateCardRequestCardGatewayBeanstream captures enum value "beanstream"
	HostedPageUpdateCardRequestCardGatewayBeanstream string = "beanstream"
	// HostedPageUpdateCardRequestCardGatewayBluepay captures enum value "bluepay"
	HostedPageUpdateCardRequestCardGatewayBluepay string = "bluepay"
	// HostedPageUpdateCardRequestCardGatewayElavon captures enum value "elavon"
	HostedPageUpdateCardRequestCardGatewayElavon string = "elavon"
	// HostedPageUpdateCardRequestCardGatewayFirstDataGlobal captures enum value "first_data_global"
	HostedPageUpdateCardRequestCardGatewayFirstDataGlobal string = "first_data_global"
	// HostedPageUpdateCardRequestCardGatewayHdfc captures enum value "hdfc"
	HostedPageUpdateCardRequestCardGatewayHdfc string = "hdfc"
	// HostedPageUpdateCardRequestCardGatewayMigs captures enum value "migs"
	HostedPageUpdateCardRequestCardGatewayMigs string = "migs"
	// HostedPageUpdateCardRequestCardGatewayNmi captures enum value "nmi"
	HostedPageUpdateCardRequestCardGatewayNmi string = "nmi"
	// HostedPageUpdateCardRequestCardGatewayOgone captures enum value "ogone"
	HostedPageUpdateCardRequestCardGatewayOgone string = "ogone"
	// HostedPageUpdateCardRequestCardGatewayPaymill captures enum value "paymill"
	HostedPageUpdateCardRequestCardGatewayPaymill string = "paymill"
	// HostedPageUpdateCardRequestCardGatewayPaypalPayflowPro captures enum value "paypal_payflow_pro"
	HostedPageUpdateCardRequestCardGatewayPaypalPayflowPro string = "paypal_payflow_pro"
	// HostedPageUpdateCardRequestCardGatewaySagePay captures enum value "sage_pay"
	HostedPageUpdateCardRequestCardGatewaySagePay string = "sage_pay"
	// HostedPageUpdateCardRequestCardGatewayTco captures enum value "tco"
	HostedPageUpdateCardRequestCardGatewayTco string = "tco"
	// HostedPageUpdateCardRequestCardGatewayWirecard captures enum value "wirecard"
	HostedPageUpdateCardRequestCardGatewayWirecard string = "wirecard"
	// HostedPageUpdateCardRequestCardGatewayAmazonPayments captures enum value "amazon_payments"
	HostedPageUpdateCardRequestCardGatewayAmazonPayments string = "amazon_payments"
	// HostedPageUpdateCardRequestCardGatewayPaypalExpressCheckout captures enum value "paypal_express_checkout"
	HostedPageUpdateCardRequestCardGatewayPaypalExpressCheckout string = "paypal_express_checkout"
	// HostedPageUpdateCardRequestCardGatewayGocardless captures enum value "gocardless"
	HostedPageUpdateCardRequestCardGatewayGocardless string = "gocardless"
	// HostedPageUpdateCardRequestCardGatewayAdyen captures enum value "adyen"
	HostedPageUpdateCardRequestCardGatewayAdyen string = "adyen"
	// HostedPageUpdateCardRequestCardGatewayOrbital captures enum value "orbital"
	HostedPageUpdateCardRequestCardGatewayOrbital string = "orbital"
	// HostedPageUpdateCardRequestCardGatewayMonerisUs captures enum value "moneris_us"
	HostedPageUpdateCardRequestCardGatewayMonerisUs string = "moneris_us"
	// HostedPageUpdateCardRequestCardGatewayMoneris captures enum value "moneris"
	HostedPageUpdateCardRequestCardGatewayMoneris string = "moneris"
	// HostedPageUpdateCardRequestCardGatewayNotApplicable captures enum value "not_applicable"
	HostedPageUpdateCardRequestCardGatewayNotApplicable string = "not_applicable"
)

// prop value enum
func (m *HostedPageUpdateCardRequest) validateCardGatewayEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, hostedPageUpdateCardRequestTypeCardGatewayPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *HostedPageUpdateCardRequest) validateCardGateway(formats strfmt.Registry) error {

	if swag.IsZero(m.CardGateway) { // not required
		return nil
	}

	// value enum
	if err := m.validateCardGatewayEnum("card[gateway]", "body", m.CardGateway); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HostedPageUpdateCardRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HostedPageUpdateCardRequest) UnmarshalBinary(b []byte) error {
	var res HostedPageUpdateCardRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
