// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HostedPageCheckoutNewRequest hosted page checkout new request
// swagger:model HostedPageCheckoutNewRequest

type HostedPageCheckoutNewRequest struct {

	// billing address city
	BillingAddressCity string `json:"billing_address[city],omitempty"`

	// billing address company
	BillingAddressCompany string `json:"billing_address[company],omitempty"`

	// billing address country
	BillingAddressCountry string `json:"billing_address[country],omitempty"`

	// billing address email
	BillingAddressEmail string `json:"billing_address[email],omitempty"`

	// billing address first name
	BillingAddressFirstName string `json:"billing_address[first_name],omitempty"`

	// billing address last name
	BillingAddressLastName string `json:"billing_address[last_name],omitempty"`

	// billing address line1
	BillingAddressLine1 string `json:"billing_address[line1],omitempty"`

	// billing address line2
	BillingAddressLine2 string `json:"billing_address[line2],omitempty"`

	// billing address line3
	BillingAddressLine3 string `json:"billing_address[line3],omitempty"`

	// billing address phone
	BillingAddressPhone string `json:"billing_address[phone],omitempty"`

	// billing address state
	BillingAddressState string `json:"billing_address[state],omitempty"`

	// billing address state code
	BillingAddressStateCode string `json:"billing_address[state_code],omitempty"`

	// billing address validation status
	BillingAddressValidationStatus string `json:"billing_address[validation_status],omitempty"`

	// billing address zip
	BillingAddressZip string `json:"billing_address[zip],omitempty"`

	// billing alignment mode
	BillingAlignmentMode string `json:"billing_alignment_mode,omitempty"`

	// billing cycles
	BillingCycles int32 `json:"billing_cycles,omitempty"`

	// cancel url
	CancelURL string `json:"cancel_url,omitempty"`

	// card gateway
	CardGateway string `json:"card[gateway],omitempty"`

	// card gateway account id
	CardGatewayAccountID string `json:"card[gateway_account_id],omitempty"`

	// customer company
	CustomerCompany string `json:"customer[company],omitempty"`

	// customer consolidated invoicing
	CustomerConsolidatedInvoicing bool `json:"customer[consolidated_invoicing],omitempty"`

	// customer email
	CustomerEmail string `json:"customer[email],omitempty"`

	// customer first name
	CustomerFirstName string `json:"customer[first_name],omitempty"`

	// customer id
	CustomerID string `json:"customer[id],omitempty"`

	// customer last name
	CustomerLastName string `json:"customer[last_name],omitempty"`

	// customer locale
	CustomerLocale string `json:"customer[locale],omitempty"`

	// customer phone
	CustomerPhone string `json:"customer[phone],omitempty"`

	// customer taxability
	CustomerTaxability string `json:"customer[taxability],omitempty"`

	// customer vat number
	CustomerVatNumber string `json:"customer[vat_number],omitempty"`

	// embed
	Embed bool `json:"embed,omitempty"`

	// iframe messaging
	IframeMessaging bool `json:"iframe_messaging,omitempty"`

	// pass thru content
	PassThruContent string `json:"pass_thru_content,omitempty"`

	// redirect url
	RedirectURL string `json:"redirect_url,omitempty"`

	// shipping address city
	ShippingAddressCity string `json:"shipping_address[city],omitempty"`

	// shipping address company
	ShippingAddressCompany string `json:"shipping_address[company],omitempty"`

	// shipping address country
	ShippingAddressCountry string `json:"shipping_address[country],omitempty"`

	// shipping address email
	ShippingAddressEmail string `json:"shipping_address[email],omitempty"`

	// shipping address first name
	ShippingAddressFirstName string `json:"shipping_address[first_name],omitempty"`

	// shipping address last name
	ShippingAddressLastName string `json:"shipping_address[last_name],omitempty"`

	// shipping address line1
	ShippingAddressLine1 string `json:"shipping_address[line1],omitempty"`

	// shipping address line2
	ShippingAddressLine2 string `json:"shipping_address[line2],omitempty"`

	// shipping address line3
	ShippingAddressLine3 string `json:"shipping_address[line3],omitempty"`

	// shipping address phone
	ShippingAddressPhone string `json:"shipping_address[phone],omitempty"`

	// shipping address state
	ShippingAddressState string `json:"shipping_address[state],omitempty"`

	// shipping address state code
	ShippingAddressStateCode string `json:"shipping_address[state_code],omitempty"`

	// shipping address validation status
	ShippingAddressValidationStatus string `json:"shipping_address[validation_status],omitempty"`

	// shipping address zip
	ShippingAddressZip string `json:"shipping_address[zip],omitempty"`

	// subscription auto collection
	SubscriptionAutoCollection string `json:"subscription[auto_collection],omitempty"`

	// subscription coupon
	SubscriptionCoupon string `json:"subscription[coupon],omitempty"`

	// subscription id
	SubscriptionID string `json:"subscription[id],omitempty"`

	// subscription invoice notes
	SubscriptionInvoiceNotes string `json:"subscription[invoice_notes],omitempty"`

	// subscription plan id
	SubscriptionPlanID string `json:"subscription[plan_id],omitempty"`

	// subscription plan quantity
	SubscriptionPlanQuantity int32 `json:"subscription[plan_quantity],omitempty"`

	// subscription plan unit price
	SubscriptionPlanUnitPrice int32 `json:"subscription[plan_unit_price],omitempty"`

	// subscription setup fee
	SubscriptionSetupFee int32 `json:"subscription[setup_fee],omitempty"`

	// subscription start date
	SubscriptionStartDate int64 `json:"subscription[start_date],omitempty"`

	// subscription trial end
	SubscriptionTrialEnd int64 `json:"subscription[trial_end],omitempty"`

	// terms to charge
	TermsToCharge int32 `json:"terms_to_charge,omitempty"`
}

/* polymorph HostedPageCheckoutNewRequest billing_address[city] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[company] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[country] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[email] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[first_name] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[last_name] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[line1] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[line2] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[line3] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[phone] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[state] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[state_code] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[validation_status] false */

/* polymorph HostedPageCheckoutNewRequest billing_address[zip] false */

/* polymorph HostedPageCheckoutNewRequest billing_alignment_mode false */

/* polymorph HostedPageCheckoutNewRequest billing_cycles false */

/* polymorph HostedPageCheckoutNewRequest cancel_url false */

/* polymorph HostedPageCheckoutNewRequest card[gateway] false */

/* polymorph HostedPageCheckoutNewRequest card[gateway_account_id] false */

/* polymorph HostedPageCheckoutNewRequest customer[company] false */

/* polymorph HostedPageCheckoutNewRequest customer[consolidated_invoicing] false */

/* polymorph HostedPageCheckoutNewRequest customer[email] false */

/* polymorph HostedPageCheckoutNewRequest customer[first_name] false */

/* polymorph HostedPageCheckoutNewRequest customer[id] false */

/* polymorph HostedPageCheckoutNewRequest customer[last_name] false */

/* polymorph HostedPageCheckoutNewRequest customer[locale] false */

/* polymorph HostedPageCheckoutNewRequest customer[phone] false */

/* polymorph HostedPageCheckoutNewRequest customer[taxability] false */

/* polymorph HostedPageCheckoutNewRequest customer[vat_number] false */

/* polymorph HostedPageCheckoutNewRequest embed false */

/* polymorph HostedPageCheckoutNewRequest iframe_messaging false */

/* polymorph HostedPageCheckoutNewRequest pass_thru_content false */

/* polymorph HostedPageCheckoutNewRequest redirect_url false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[city] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[company] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[country] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[email] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[first_name] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[last_name] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[line1] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[line2] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[line3] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[phone] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[state] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[state_code] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[validation_status] false */

/* polymorph HostedPageCheckoutNewRequest shipping_address[zip] false */

/* polymorph HostedPageCheckoutNewRequest subscription[auto_collection] false */

/* polymorph HostedPageCheckoutNewRequest subscription[coupon] false */

/* polymorph HostedPageCheckoutNewRequest subscription[id] false */

/* polymorph HostedPageCheckoutNewRequest subscription[invoice_notes] false */

/* polymorph HostedPageCheckoutNewRequest subscription[plan_id] false */

/* polymorph HostedPageCheckoutNewRequest subscription[plan_quantity] false */

/* polymorph HostedPageCheckoutNewRequest subscription[plan_unit_price] false */

/* polymorph HostedPageCheckoutNewRequest subscription[setup_fee] false */

/* polymorph HostedPageCheckoutNewRequest subscription[start_date] false */

/* polymorph HostedPageCheckoutNewRequest subscription[trial_end] false */

/* polymorph HostedPageCheckoutNewRequest terms_to_charge false */

// Validate validates this hosted page checkout new request
func (m *HostedPageCheckoutNewRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBillingAddressValidationStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateBillingAlignmentMode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCardGateway(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCustomerTaxability(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateShippingAddressValidationStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateSubscriptionAutoCollection(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var hostedPageCheckoutNewRequestTypeBillingAddressValidationStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["not_validated","valid","partially_valid","invalid"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hostedPageCheckoutNewRequestTypeBillingAddressValidationStatusPropEnum = append(hostedPageCheckoutNewRequestTypeBillingAddressValidationStatusPropEnum, v)
	}
}

const (
	// HostedPageCheckoutNewRequestBillingAddressValidationStatusNotValidated captures enum value "not_validated"
	HostedPageCheckoutNewRequestBillingAddressValidationStatusNotValidated string = "not_validated"
	// HostedPageCheckoutNewRequestBillingAddressValidationStatusValid captures enum value "valid"
	HostedPageCheckoutNewRequestBillingAddressValidationStatusValid string = "valid"
	// HostedPageCheckoutNewRequestBillingAddressValidationStatusPartiallyValid captures enum value "partially_valid"
	HostedPageCheckoutNewRequestBillingAddressValidationStatusPartiallyValid string = "partially_valid"
	// HostedPageCheckoutNewRequestBillingAddressValidationStatusInvalid captures enum value "invalid"
	HostedPageCheckoutNewRequestBillingAddressValidationStatusInvalid string = "invalid"
)

// prop value enum
func (m *HostedPageCheckoutNewRequest) validateBillingAddressValidationStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, hostedPageCheckoutNewRequestTypeBillingAddressValidationStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *HostedPageCheckoutNewRequest) validateBillingAddressValidationStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.BillingAddressValidationStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateBillingAddressValidationStatusEnum("billing_address[validation_status]", "body", m.BillingAddressValidationStatus); err != nil {
		return err
	}

	return nil
}

var hostedPageCheckoutNewRequestTypeBillingAlignmentModePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["immediate","delayed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hostedPageCheckoutNewRequestTypeBillingAlignmentModePropEnum = append(hostedPageCheckoutNewRequestTypeBillingAlignmentModePropEnum, v)
	}
}

const (
	// HostedPageCheckoutNewRequestBillingAlignmentModeImmediate captures enum value "immediate"
	HostedPageCheckoutNewRequestBillingAlignmentModeImmediate string = "immediate"
	// HostedPageCheckoutNewRequestBillingAlignmentModeDelayed captures enum value "delayed"
	HostedPageCheckoutNewRequestBillingAlignmentModeDelayed string = "delayed"
)

// prop value enum
func (m *HostedPageCheckoutNewRequest) validateBillingAlignmentModeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, hostedPageCheckoutNewRequestTypeBillingAlignmentModePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *HostedPageCheckoutNewRequest) validateBillingAlignmentMode(formats strfmt.Registry) error {

	if swag.IsZero(m.BillingAlignmentMode) { // not required
		return nil
	}

	// value enum
	if err := m.validateBillingAlignmentModeEnum("billing_alignment_mode", "body", m.BillingAlignmentMode); err != nil {
		return err
	}

	return nil
}

var hostedPageCheckoutNewRequestTypeCardGatewayPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["chargebee","stripe","wepay","braintree","authorize_net","paypal_pro","pin","eway","eway_rapid","worldpay","balanced_payments","beanstream","bluepay","elavon","first_data_global","hdfc","migs","nmi","ogone","paymill","paypal_payflow_pro","sage_pay","tco","wirecard","amazon_payments","paypal_express_checkout","gocardless","adyen","orbital","moneris_us","moneris","not_applicable"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hostedPageCheckoutNewRequestTypeCardGatewayPropEnum = append(hostedPageCheckoutNewRequestTypeCardGatewayPropEnum, v)
	}
}

const (
	// HostedPageCheckoutNewRequestCardGatewayChargebee captures enum value "chargebee"
	HostedPageCheckoutNewRequestCardGatewayChargebee string = "chargebee"
	// HostedPageCheckoutNewRequestCardGatewayStripe captures enum value "stripe"
	HostedPageCheckoutNewRequestCardGatewayStripe string = "stripe"
	// HostedPageCheckoutNewRequestCardGatewayWepay captures enum value "wepay"
	HostedPageCheckoutNewRequestCardGatewayWepay string = "wepay"
	// HostedPageCheckoutNewRequestCardGatewayBraintree captures enum value "braintree"
	HostedPageCheckoutNewRequestCardGatewayBraintree string = "braintree"
	// HostedPageCheckoutNewRequestCardGatewayAuthorizeNet captures enum value "authorize_net"
	HostedPageCheckoutNewRequestCardGatewayAuthorizeNet string = "authorize_net"
	// HostedPageCheckoutNewRequestCardGatewayPaypalPro captures enum value "paypal_pro"
	HostedPageCheckoutNewRequestCardGatewayPaypalPro string = "paypal_pro"
	// HostedPageCheckoutNewRequestCardGatewayPin captures enum value "pin"
	HostedPageCheckoutNewRequestCardGatewayPin string = "pin"
	// HostedPageCheckoutNewRequestCardGatewayEway captures enum value "eway"
	HostedPageCheckoutNewRequestCardGatewayEway string = "eway"
	// HostedPageCheckoutNewRequestCardGatewayEwayRapid captures enum value "eway_rapid"
	HostedPageCheckoutNewRequestCardGatewayEwayRapid string = "eway_rapid"
	// HostedPageCheckoutNewRequestCardGatewayWorldpay captures enum value "worldpay"
	HostedPageCheckoutNewRequestCardGatewayWorldpay string = "worldpay"
	// HostedPageCheckoutNewRequestCardGatewayBalancedPayments captures enum value "balanced_payments"
	HostedPageCheckoutNewRequestCardGatewayBalancedPayments string = "balanced_payments"
	// HostedPageCheckoutNewRequestCardGatewayBeanstream captures enum value "beanstream"
	HostedPageCheckoutNewRequestCardGatewayBeanstream string = "beanstream"
	// HostedPageCheckoutNewRequestCardGatewayBluepay captures enum value "bluepay"
	HostedPageCheckoutNewRequestCardGatewayBluepay string = "bluepay"
	// HostedPageCheckoutNewRequestCardGatewayElavon captures enum value "elavon"
	HostedPageCheckoutNewRequestCardGatewayElavon string = "elavon"
	// HostedPageCheckoutNewRequestCardGatewayFirstDataGlobal captures enum value "first_data_global"
	HostedPageCheckoutNewRequestCardGatewayFirstDataGlobal string = "first_data_global"
	// HostedPageCheckoutNewRequestCardGatewayHdfc captures enum value "hdfc"
	HostedPageCheckoutNewRequestCardGatewayHdfc string = "hdfc"
	// HostedPageCheckoutNewRequestCardGatewayMigs captures enum value "migs"
	HostedPageCheckoutNewRequestCardGatewayMigs string = "migs"
	// HostedPageCheckoutNewRequestCardGatewayNmi captures enum value "nmi"
	HostedPageCheckoutNewRequestCardGatewayNmi string = "nmi"
	// HostedPageCheckoutNewRequestCardGatewayOgone captures enum value "ogone"
	HostedPageCheckoutNewRequestCardGatewayOgone string = "ogone"
	// HostedPageCheckoutNewRequestCardGatewayPaymill captures enum value "paymill"
	HostedPageCheckoutNewRequestCardGatewayPaymill string = "paymill"
	// HostedPageCheckoutNewRequestCardGatewayPaypalPayflowPro captures enum value "paypal_payflow_pro"
	HostedPageCheckoutNewRequestCardGatewayPaypalPayflowPro string = "paypal_payflow_pro"
	// HostedPageCheckoutNewRequestCardGatewaySagePay captures enum value "sage_pay"
	HostedPageCheckoutNewRequestCardGatewaySagePay string = "sage_pay"
	// HostedPageCheckoutNewRequestCardGatewayTco captures enum value "tco"
	HostedPageCheckoutNewRequestCardGatewayTco string = "tco"
	// HostedPageCheckoutNewRequestCardGatewayWirecard captures enum value "wirecard"
	HostedPageCheckoutNewRequestCardGatewayWirecard string = "wirecard"
	// HostedPageCheckoutNewRequestCardGatewayAmazonPayments captures enum value "amazon_payments"
	HostedPageCheckoutNewRequestCardGatewayAmazonPayments string = "amazon_payments"
	// HostedPageCheckoutNewRequestCardGatewayPaypalExpressCheckout captures enum value "paypal_express_checkout"
	HostedPageCheckoutNewRequestCardGatewayPaypalExpressCheckout string = "paypal_express_checkout"
	// HostedPageCheckoutNewRequestCardGatewayGocardless captures enum value "gocardless"
	HostedPageCheckoutNewRequestCardGatewayGocardless string = "gocardless"
	// HostedPageCheckoutNewRequestCardGatewayAdyen captures enum value "adyen"
	HostedPageCheckoutNewRequestCardGatewayAdyen string = "adyen"
	// HostedPageCheckoutNewRequestCardGatewayOrbital captures enum value "orbital"
	HostedPageCheckoutNewRequestCardGatewayOrbital string = "orbital"
	// HostedPageCheckoutNewRequestCardGatewayMonerisUs captures enum value "moneris_us"
	HostedPageCheckoutNewRequestCardGatewayMonerisUs string = "moneris_us"
	// HostedPageCheckoutNewRequestCardGatewayMoneris captures enum value "moneris"
	HostedPageCheckoutNewRequestCardGatewayMoneris string = "moneris"
	// HostedPageCheckoutNewRequestCardGatewayNotApplicable captures enum value "not_applicable"
	HostedPageCheckoutNewRequestCardGatewayNotApplicable string = "not_applicable"
)

// prop value enum
func (m *HostedPageCheckoutNewRequest) validateCardGatewayEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, hostedPageCheckoutNewRequestTypeCardGatewayPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *HostedPageCheckoutNewRequest) validateCardGateway(formats strfmt.Registry) error {

	if swag.IsZero(m.CardGateway) { // not required
		return nil
	}

	// value enum
	if err := m.validateCardGatewayEnum("card[gateway]", "body", m.CardGateway); err != nil {
		return err
	}

	return nil
}

var hostedPageCheckoutNewRequestTypeCustomerTaxabilityPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["taxable","exempt"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hostedPageCheckoutNewRequestTypeCustomerTaxabilityPropEnum = append(hostedPageCheckoutNewRequestTypeCustomerTaxabilityPropEnum, v)
	}
}

const (
	// HostedPageCheckoutNewRequestCustomerTaxabilityTaxable captures enum value "taxable"
	HostedPageCheckoutNewRequestCustomerTaxabilityTaxable string = "taxable"
	// HostedPageCheckoutNewRequestCustomerTaxabilityExempt captures enum value "exempt"
	HostedPageCheckoutNewRequestCustomerTaxabilityExempt string = "exempt"
)

// prop value enum
func (m *HostedPageCheckoutNewRequest) validateCustomerTaxabilityEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, hostedPageCheckoutNewRequestTypeCustomerTaxabilityPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *HostedPageCheckoutNewRequest) validateCustomerTaxability(formats strfmt.Registry) error {

	if swag.IsZero(m.CustomerTaxability) { // not required
		return nil
	}

	// value enum
	if err := m.validateCustomerTaxabilityEnum("customer[taxability]", "body", m.CustomerTaxability); err != nil {
		return err
	}

	return nil
}

var hostedPageCheckoutNewRequestTypeShippingAddressValidationStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["not_validated","valid","partially_valid","invalid"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hostedPageCheckoutNewRequestTypeShippingAddressValidationStatusPropEnum = append(hostedPageCheckoutNewRequestTypeShippingAddressValidationStatusPropEnum, v)
	}
}

const (
	// HostedPageCheckoutNewRequestShippingAddressValidationStatusNotValidated captures enum value "not_validated"
	HostedPageCheckoutNewRequestShippingAddressValidationStatusNotValidated string = "not_validated"
	// HostedPageCheckoutNewRequestShippingAddressValidationStatusValid captures enum value "valid"
	HostedPageCheckoutNewRequestShippingAddressValidationStatusValid string = "valid"
	// HostedPageCheckoutNewRequestShippingAddressValidationStatusPartiallyValid captures enum value "partially_valid"
	HostedPageCheckoutNewRequestShippingAddressValidationStatusPartiallyValid string = "partially_valid"
	// HostedPageCheckoutNewRequestShippingAddressValidationStatusInvalid captures enum value "invalid"
	HostedPageCheckoutNewRequestShippingAddressValidationStatusInvalid string = "invalid"
)

// prop value enum
func (m *HostedPageCheckoutNewRequest) validateShippingAddressValidationStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, hostedPageCheckoutNewRequestTypeShippingAddressValidationStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *HostedPageCheckoutNewRequest) validateShippingAddressValidationStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.ShippingAddressValidationStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateShippingAddressValidationStatusEnum("shipping_address[validation_status]", "body", m.ShippingAddressValidationStatus); err != nil {
		return err
	}

	return nil
}

var hostedPageCheckoutNewRequestTypeSubscriptionAutoCollectionPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["on","off"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hostedPageCheckoutNewRequestTypeSubscriptionAutoCollectionPropEnum = append(hostedPageCheckoutNewRequestTypeSubscriptionAutoCollectionPropEnum, v)
	}
}

const (
	// HostedPageCheckoutNewRequestSubscriptionAutoCollectionOn captures enum value "on"
	HostedPageCheckoutNewRequestSubscriptionAutoCollectionOn string = "on"
	// HostedPageCheckoutNewRequestSubscriptionAutoCollectionOff captures enum value "off"
	HostedPageCheckoutNewRequestSubscriptionAutoCollectionOff string = "off"
)

// prop value enum
func (m *HostedPageCheckoutNewRequest) validateSubscriptionAutoCollectionEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, hostedPageCheckoutNewRequestTypeSubscriptionAutoCollectionPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *HostedPageCheckoutNewRequest) validateSubscriptionAutoCollection(formats strfmt.Registry) error {

	if swag.IsZero(m.SubscriptionAutoCollection) { // not required
		return nil
	}

	// value enum
	if err := m.validateSubscriptionAutoCollectionEnum("subscription[auto_collection]", "body", m.SubscriptionAutoCollection); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HostedPageCheckoutNewRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HostedPageCheckoutNewRequest) UnmarshalBinary(b []byte) error {
	var res HostedPageCheckoutNewRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
