// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InvoiceRecordPaymentRequest invoice record payment request
// swagger:model InvoiceRecordPaymentRequest

type InvoiceRecordPaymentRequest struct {

	// comment
	Comment string `json:"comment,omitempty"`

	// transaction amount
	TransactionAmount int32 `json:"transaction[amount],omitempty"`

	// transaction date
	TransactionDate int64 `json:"transaction[date],omitempty"`

	// transaction error code
	TransactionErrorCode string `json:"transaction[error_code],omitempty"`

	// transaction error text
	TransactionErrorText string `json:"transaction[error_text],omitempty"`

	// transaction id at gateway
	TransactionIDAtGateway string `json:"transaction[id_at_gateway],omitempty"`

	// transaction payment method
	TransactionPaymentMethod *PaymentMethod `json:"transaction[payment_method],omitempty"`

	// transaction reference number
	TransactionReferenceNumber string `json:"transaction[reference_number],omitempty"`

	// transaction status
	TransactionStatus string `json:"transaction[status],omitempty"`
}

/* polymorph InvoiceRecordPaymentRequest comment false */

/* polymorph InvoiceRecordPaymentRequest transaction[amount] false */

/* polymorph InvoiceRecordPaymentRequest transaction[date] false */

/* polymorph InvoiceRecordPaymentRequest transaction[error_code] false */

/* polymorph InvoiceRecordPaymentRequest transaction[error_text] false */

/* polymorph InvoiceRecordPaymentRequest transaction[id_at_gateway] false */

/* polymorph InvoiceRecordPaymentRequest transaction[payment_method] false */

/* polymorph InvoiceRecordPaymentRequest transaction[reference_number] false */

/* polymorph InvoiceRecordPaymentRequest transaction[status] false */

// Validate validates this invoice record payment request
func (m *InvoiceRecordPaymentRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTransactionPaymentMethod(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateTransactionStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *InvoiceRecordPaymentRequest) validateTransactionPaymentMethod(formats strfmt.Registry) error {

	if swag.IsZero(m.TransactionPaymentMethod) { // not required
		return nil
	}

	if m.TransactionPaymentMethod != nil {

		if err := m.TransactionPaymentMethod.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("transaction[payment_method]")
			}
			return err
		}
	}

	return nil
}

var invoiceRecordPaymentRequestTypeTransactionStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["in_progress","success","voided","failure","timeout","needs_attention"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		invoiceRecordPaymentRequestTypeTransactionStatusPropEnum = append(invoiceRecordPaymentRequestTypeTransactionStatusPropEnum, v)
	}
}

const (
	// InvoiceRecordPaymentRequestTransactionStatusInProgress captures enum value "in_progress"
	InvoiceRecordPaymentRequestTransactionStatusInProgress string = "in_progress"
	// InvoiceRecordPaymentRequestTransactionStatusSuccess captures enum value "success"
	InvoiceRecordPaymentRequestTransactionStatusSuccess string = "success"
	// InvoiceRecordPaymentRequestTransactionStatusVoided captures enum value "voided"
	InvoiceRecordPaymentRequestTransactionStatusVoided string = "voided"
	// InvoiceRecordPaymentRequestTransactionStatusFailure captures enum value "failure"
	InvoiceRecordPaymentRequestTransactionStatusFailure string = "failure"
	// InvoiceRecordPaymentRequestTransactionStatusTimeout captures enum value "timeout"
	InvoiceRecordPaymentRequestTransactionStatusTimeout string = "timeout"
	// InvoiceRecordPaymentRequestTransactionStatusNeedsAttention captures enum value "needs_attention"
	InvoiceRecordPaymentRequestTransactionStatusNeedsAttention string = "needs_attention"
)

// prop value enum
func (m *InvoiceRecordPaymentRequest) validateTransactionStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, invoiceRecordPaymentRequestTypeTransactionStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *InvoiceRecordPaymentRequest) validateTransactionStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.TransactionStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateTransactionStatusEnum("transaction[status]", "body", m.TransactionStatus); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InvoiceRecordPaymentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InvoiceRecordPaymentRequest) UnmarshalBinary(b []byte) error {
	var res InvoiceRecordPaymentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
