// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InvoiceAddChargeRequest invoice add charge request
// swagger:model InvoiceAddChargeRequest

type InvoiceAddChargeRequest struct {

	// amount
	Amount int32 `json:"amount,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// line item date from
	LineItemDateFrom int64 `json:"line_item[date_from],omitempty"`

	// line item date to
	LineItemDateTo int64 `json:"line_item[date_to],omitempty"`
}

/* polymorph InvoiceAddChargeRequest amount false */

/* polymorph InvoiceAddChargeRequest description false */

/* polymorph InvoiceAddChargeRequest line_item[date_from] false */

/* polymorph InvoiceAddChargeRequest line_item[date_to] false */

// Validate validates this invoice add charge request
func (m *InvoiceAddChargeRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *InvoiceAddChargeRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InvoiceAddChargeRequest) UnmarshalBinary(b []byte) error {
	var res InvoiceAddChargeRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
