// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// InvoiceCollectPaymentRequest invoice collect payment request
// swagger:model InvoiceCollectPaymentRequest

type InvoiceCollectPaymentRequest struct {

	// amount
	Amount int32 `json:"amount,omitempty"`

	// payment source id
	PaymentSourceID string `json:"payment_source_id,omitempty"`
}

/* polymorph InvoiceCollectPaymentRequest amount false */

/* polymorph InvoiceCollectPaymentRequest payment_source_id false */

// Validate validates this invoice collect payment request
func (m *InvoiceCollectPaymentRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *InvoiceCollectPaymentRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InvoiceCollectPaymentRequest) UnmarshalBinary(b []byte) error {
	var res InvoiceCollectPaymentRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
