// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// InvoiceRefundRequest invoice refund request
// swagger:model InvoiceRefundRequest

type InvoiceRefundRequest struct {

	// comment
	Comment string `json:"comment,omitempty"`

	// credit note reason code
	CreditNoteReasonCode string `json:"credit_note[reason_code],omitempty"`

	// customer notes
	CustomerNotes string `json:"customer_notes,omitempty"`

	// refund amount
	RefundAmount int32 `json:"refund_amount,omitempty"`
}

/* polymorph InvoiceRefundRequest comment false */

/* polymorph InvoiceRefundRequest credit_note[reason_code] false */

/* polymorph InvoiceRefundRequest customer_notes false */

/* polymorph InvoiceRefundRequest refund_amount false */

// Validate validates this invoice refund request
func (m *InvoiceRefundRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreditNoteReasonCode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var invoiceRefundRequestTypeCreditNoteReasonCodePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["write_off","subscription_change","subscription_cancellation","chargeback","product_unsatisfactory","service_unsatisfactory","order_change","order_cancellation","waiver","other","fraudulent"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		invoiceRefundRequestTypeCreditNoteReasonCodePropEnum = append(invoiceRefundRequestTypeCreditNoteReasonCodePropEnum, v)
	}
}

const (
	// InvoiceRefundRequestCreditNoteReasonCodeWriteOff captures enum value "write_off"
	InvoiceRefundRequestCreditNoteReasonCodeWriteOff string = "write_off"
	// InvoiceRefundRequestCreditNoteReasonCodeSubscriptionChange captures enum value "subscription_change"
	InvoiceRefundRequestCreditNoteReasonCodeSubscriptionChange string = "subscription_change"
	// InvoiceRefundRequestCreditNoteReasonCodeSubscriptionCancellation captures enum value "subscription_cancellation"
	InvoiceRefundRequestCreditNoteReasonCodeSubscriptionCancellation string = "subscription_cancellation"
	// InvoiceRefundRequestCreditNoteReasonCodeChargeback captures enum value "chargeback"
	InvoiceRefundRequestCreditNoteReasonCodeChargeback string = "chargeback"
	// InvoiceRefundRequestCreditNoteReasonCodeProductUnsatisfactory captures enum value "product_unsatisfactory"
	InvoiceRefundRequestCreditNoteReasonCodeProductUnsatisfactory string = "product_unsatisfactory"
	// InvoiceRefundRequestCreditNoteReasonCodeServiceUnsatisfactory captures enum value "service_unsatisfactory"
	InvoiceRefundRequestCreditNoteReasonCodeServiceUnsatisfactory string = "service_unsatisfactory"
	// InvoiceRefundRequestCreditNoteReasonCodeOrderChange captures enum value "order_change"
	InvoiceRefundRequestCreditNoteReasonCodeOrderChange string = "order_change"
	// InvoiceRefundRequestCreditNoteReasonCodeOrderCancellation captures enum value "order_cancellation"
	InvoiceRefundRequestCreditNoteReasonCodeOrderCancellation string = "order_cancellation"
	// InvoiceRefundRequestCreditNoteReasonCodeWaiver captures enum value "waiver"
	InvoiceRefundRequestCreditNoteReasonCodeWaiver string = "waiver"
	// InvoiceRefundRequestCreditNoteReasonCodeOther captures enum value "other"
	InvoiceRefundRequestCreditNoteReasonCodeOther string = "other"
	// InvoiceRefundRequestCreditNoteReasonCodeFraudulent captures enum value "fraudulent"
	InvoiceRefundRequestCreditNoteReasonCodeFraudulent string = "fraudulent"
)

// prop value enum
func (m *InvoiceRefundRequest) validateCreditNoteReasonCodeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, invoiceRefundRequestTypeCreditNoteReasonCodePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *InvoiceRefundRequest) validateCreditNoteReasonCode(formats strfmt.Registry) error {

	if swag.IsZero(m.CreditNoteReasonCode) { // not required
		return nil
	}

	// value enum
	if err := m.validateCreditNoteReasonCodeEnum("credit_note[reason_code]", "body", m.CreditNoteReasonCode); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *InvoiceRefundRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *InvoiceRefundRequest) UnmarshalBinary(b []byte) error {
	var res InvoiceRefundRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
