// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LinkedInvoice linked invoice
// swagger:model LinkedInvoice

type LinkedInvoice struct {

	// applied amount
	AppliedAmount int32 `json:"applied_amount,omitempty"`

	// applied at
	AppliedAt int64 `json:"applied_at,omitempty"`

	// invoice date
	InvoiceDate int64 `json:"invoice_date,omitempty"`

	// invoice id
	InvoiceID string `json:"invoice_id,omitempty"`

	// invoice status
	InvoiceStatus string `json:"invoice_status,omitempty"`

	// invoice total
	InvoiceTotal int32 `json:"invoice_total,omitempty"`
}

/* polymorph LinkedInvoice applied_amount false */

/* polymorph LinkedInvoice applied_at false */

/* polymorph LinkedInvoice invoice_date false */

/* polymorph LinkedInvoice invoice_id false */

/* polymorph LinkedInvoice invoice_status false */

/* polymorph LinkedInvoice invoice_total false */

// Validate validates this linked invoice
func (m *LinkedInvoice) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateInvoiceStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var linkedInvoiceTypeInvoiceStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["in_progress","success","voided","failure","timeout","needs_attention"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		linkedInvoiceTypeInvoiceStatusPropEnum = append(linkedInvoiceTypeInvoiceStatusPropEnum, v)
	}
}

const (
	// LinkedInvoiceInvoiceStatusInProgress captures enum value "in_progress"
	LinkedInvoiceInvoiceStatusInProgress string = "in_progress"
	// LinkedInvoiceInvoiceStatusSuccess captures enum value "success"
	LinkedInvoiceInvoiceStatusSuccess string = "success"
	// LinkedInvoiceInvoiceStatusVoided captures enum value "voided"
	LinkedInvoiceInvoiceStatusVoided string = "voided"
	// LinkedInvoiceInvoiceStatusFailure captures enum value "failure"
	LinkedInvoiceInvoiceStatusFailure string = "failure"
	// LinkedInvoiceInvoiceStatusTimeout captures enum value "timeout"
	LinkedInvoiceInvoiceStatusTimeout string = "timeout"
	// LinkedInvoiceInvoiceStatusNeedsAttention captures enum value "needs_attention"
	LinkedInvoiceInvoiceStatusNeedsAttention string = "needs_attention"
)

// prop value enum
func (m *LinkedInvoice) validateInvoiceStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, linkedInvoiceTypeInvoiceStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *LinkedInvoice) validateInvoiceStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.InvoiceStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateInvoiceStatusEnum("invoice_status", "body", m.InvoiceStatus); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LinkedInvoice) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LinkedInvoice) UnmarshalBinary(b []byte) error {
	var res LinkedInvoice
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
