// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// LinkedCreditNote linked credit note
// swagger:model LinkedCreditNote
type LinkedCreditNote struct {

	// applied amount
	AppliedAmount int32 `json:"applied_amount,omitempty"`

	// applied at
	AppliedAt int64 `json:"applied_at,omitempty"`

	// cn date
	CnDate int64 `json:"cn_date,omitempty"`

	// cn id
	CnID string `json:"cn_id,omitempty"`

	// cn reason code
	CnReasonCode string `json:"cn_reason_code,omitempty"`

	// cn reference invoice id
	CnReferenceInvoiceID string `json:"cn_reference_invoice_id,omitempty"`

	// cn status
	CnStatus string `json:"cn_status,omitempty"`

	// cn total
	CnTotal int32 `json:"cn_total,omitempty"`
}

// Validate validates this linked credit note
func (m *LinkedCreditNote) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCnReasonCode(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if err := m.validateCnStatus(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var linkedCreditNoteTypeCnReasonCodePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["write_off","subscription_change","subscription_cancellation","chargeback","product_unsatisfactory","service_unsatisfactory","order_change","order_cancellation","waiver","other","fraudulent"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		linkedCreditNoteTypeCnReasonCodePropEnum = append(linkedCreditNoteTypeCnReasonCodePropEnum, v)
	}
}

const (

	// LinkedCreditNoteCnReasonCodeWriteOff captures enum value "write_off"
	LinkedCreditNoteCnReasonCodeWriteOff string = "write_off"

	// LinkedCreditNoteCnReasonCodeSubscriptionChange captures enum value "subscription_change"
	LinkedCreditNoteCnReasonCodeSubscriptionChange string = "subscription_change"

	// LinkedCreditNoteCnReasonCodeSubscriptionCancellation captures enum value "subscription_cancellation"
	LinkedCreditNoteCnReasonCodeSubscriptionCancellation string = "subscription_cancellation"

	// LinkedCreditNoteCnReasonCodeChargeback captures enum value "chargeback"
	LinkedCreditNoteCnReasonCodeChargeback string = "chargeback"

	// LinkedCreditNoteCnReasonCodeProductUnsatisfactory captures enum value "product_unsatisfactory"
	LinkedCreditNoteCnReasonCodeProductUnsatisfactory string = "product_unsatisfactory"

	// LinkedCreditNoteCnReasonCodeServiceUnsatisfactory captures enum value "service_unsatisfactory"
	LinkedCreditNoteCnReasonCodeServiceUnsatisfactory string = "service_unsatisfactory"

	// LinkedCreditNoteCnReasonCodeOrderChange captures enum value "order_change"
	LinkedCreditNoteCnReasonCodeOrderChange string = "order_change"

	// LinkedCreditNoteCnReasonCodeOrderCancellation captures enum value "order_cancellation"
	LinkedCreditNoteCnReasonCodeOrderCancellation string = "order_cancellation"

	// LinkedCreditNoteCnReasonCodeWaiver captures enum value "waiver"
	LinkedCreditNoteCnReasonCodeWaiver string = "waiver"

	// LinkedCreditNoteCnReasonCodeOther captures enum value "other"
	LinkedCreditNoteCnReasonCodeOther string = "other"

	// LinkedCreditNoteCnReasonCodeFraudulent captures enum value "fraudulent"
	LinkedCreditNoteCnReasonCodeFraudulent string = "fraudulent"
)

// prop value enum
func (m *LinkedCreditNote) validateCnReasonCodeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, linkedCreditNoteTypeCnReasonCodePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *LinkedCreditNote) validateCnReasonCode(formats strfmt.Registry) error {

	if swag.IsZero(m.CnReasonCode) { // not required
		return nil
	}

	// value enum
	if err := m.validateCnReasonCodeEnum("cn_reason_code", "body", m.CnReasonCode); err != nil {
		return err
	}

	return nil
}

var linkedCreditNoteTypeCnStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["future","in_trial","active","non_renewing","cancelled"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		linkedCreditNoteTypeCnStatusPropEnum = append(linkedCreditNoteTypeCnStatusPropEnum, v)
	}
}

const (

	// LinkedCreditNoteCnStatusFuture captures enum value "future"
	LinkedCreditNoteCnStatusFuture string = "future"

	// LinkedCreditNoteCnStatusInTrial captures enum value "in_trial"
	LinkedCreditNoteCnStatusInTrial string = "in_trial"

	// LinkedCreditNoteCnStatusActive captures enum value "active"
	LinkedCreditNoteCnStatusActive string = "active"

	// LinkedCreditNoteCnStatusNonRenewing captures enum value "non_renewing"
	LinkedCreditNoteCnStatusNonRenewing string = "non_renewing"

	// LinkedCreditNoteCnStatusCancelled captures enum value "cancelled"
	LinkedCreditNoteCnStatusCancelled string = "cancelled"
)

// prop value enum
func (m *LinkedCreditNote) validateCnStatusEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, linkedCreditNoteTypeCnStatusPropEnum); err != nil {
		return err
	}
	return nil
}

func (m *LinkedCreditNote) validateCnStatus(formats strfmt.Registry) error {

	if swag.IsZero(m.CnStatus) { // not required
		return nil
	}

	// value enum
	if err := m.validateCnStatusEnum("cn_status", "body", m.CnStatus); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *LinkedCreditNote) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *LinkedCreditNote) UnmarshalBinary(b []byte) error {
	var res LinkedCreditNote
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
