// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PortalSessionResponse portal session response
// swagger:model PortalSessionResponse

type PortalSessionResponse struct {

	// portalsession
	Portalsession *PortalSession `json:"portalsession,omitempty"`
}

/* polymorph PortalSessionResponse portalsession false */

// Validate validates this portal session response
func (m *PortalSessionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePortalsession(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PortalSessionResponse) validatePortalsession(formats strfmt.Registry) error {

	if swag.IsZero(m.Portalsession) { // not required
		return nil
	}

	if m.Portalsession != nil {

		if err := m.Portalsession.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("portalsession")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PortalSessionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PortalSessionResponse) UnmarshalBinary(b []byte) error {
	var res PortalSessionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
