// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PromotionalCreditAddRequest promotional credit add request
// swagger:model PromotionalCreditAddRequest
type PromotionalCreditAddRequest struct {

	// amount
	Amount int32 `json:"amount,omitempty"`

	// credit type
	CreditType string `json:"credit_type,omitempty"`

	// currency code
	CurrencyCode string `json:"currency_code,omitempty"`

	// customer id
	CustomerID string `json:"customer_id,omitempty"`

	// description
	Description string `json:"description,omitempty"`

	// reference
	Reference string `json:"reference,omitempty"`
}

// Validate validates this promotional credit add request
func (m *PromotionalCreditAddRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreditType(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

var promotionalCreditAddRequestTypeCreditTypePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["loyalty_credits","referral_rewards","general"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		promotionalCreditAddRequestTypeCreditTypePropEnum = append(promotionalCreditAddRequestTypeCreditTypePropEnum, v)
	}
}

const (

	// PromotionalCreditAddRequestCreditTypeLoyaltyCredits captures enum value "loyalty_credits"
	PromotionalCreditAddRequestCreditTypeLoyaltyCredits string = "loyalty_credits"

	// PromotionalCreditAddRequestCreditTypeReferralRewards captures enum value "referral_rewards"
	PromotionalCreditAddRequestCreditTypeReferralRewards string = "referral_rewards"

	// PromotionalCreditAddRequestCreditTypeGeneral captures enum value "general"
	PromotionalCreditAddRequestCreditTypeGeneral string = "general"
)

// prop value enum
func (m *PromotionalCreditAddRequest) validateCreditTypeEnum(path, location string, value string) error {
	if err := validate.Enum(path, location, value, promotionalCreditAddRequestTypeCreditTypePropEnum); err != nil {
		return err
	}
	return nil
}

func (m *PromotionalCreditAddRequest) validateCreditType(formats strfmt.Registry) error {

	if swag.IsZero(m.CreditType) { // not required
		return nil
	}

	// value enum
	if err := m.validateCreditTypeEnum("credit_type", "body", m.CreditType); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PromotionalCreditAddRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PromotionalCreditAddRequest) UnmarshalBinary(b []byte) error {
	var res PromotionalCreditAddRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
