// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TimeMachineResponse time machine response
// swagger:model TimeMachineResponse
type TimeMachineResponse struct {

	// timemachine
	Timemachine *TimeMachine `json:"timemachine,omitempty"`
}

// Validate validates this time machine response
func (m *TimeMachineResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTimemachine(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TimeMachineResponse) validateTimemachine(formats strfmt.Registry) error {

	if swag.IsZero(m.Timemachine) { // not required
		return nil
	}

	if m.Timemachine != nil {

		if err := m.Timemachine.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("timemachine")
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *TimeMachineResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TimeMachineResponse) UnmarshalBinary(b []byte) error {
	var res TimeMachineResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
